"""Image library endpoints — generate and list user images."""
import logging
import uuid
from datetime import datetime, timedelta
from pathlib import Path

from fastapi import APIRouter, Depends, HTTPException, status
from pydantic import BaseModel, Field
from sqlalchemy.orm import Session

from app.core.config import settings
from app.core.database import get_db
from app.core.dependencies import get_current_user
from app.models.character import Character
from app.models.character_image import CharacterImage, ImageKindEnum, ImageStatusEnum
from app.models.user import User
from app.schemas.character_image import CharacterImageCreate, CharacterImageRead
from app.services.character_visual import create_character_image
from app.services.image_provider import get_image_provider, get_fallback_provider
from app.services.stub_image_generator import generate_placeholder_png

logger = logging.getLogger(__name__)

router = APIRouter()

_GENERATED_DIR = Path(__file__).resolve().parent.parent.parent.parent / "static" / "generated"


class ImageGenerateRequest(BaseModel):
    prompt: str = Field(..., min_length=1, max_length=250)


# ── Helpers ───────────────────────────────────────────────────────────────────

def _save_png_bytes(png_bytes: bytes) -> str:
    """Write PNG bytes to static/generated/<uuid>.png. Return relative file_path."""
    _GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    filename = f"{uuid.uuid4().hex}.png"
    (_GENERATED_DIR / filename).write_bytes(png_bytes)
    return f"static/generated/{filename}"


def _pick_character(db: Session, user: User) -> Character:
    """Pick the best character owned by *user* for library images."""
    chars = (
        db.query(Character)
        .filter(Character.owner_id == user.id)
        .order_by(Character.created_at)
        .all()
    )
    if not chars:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="You need to create a character before generating images.",
        )
    # Prefer a visually-locked character
    for c in chars:
        if c.visual_locked:
            return c
    return chars[0]


def _count_weekly_library_images(db: Session, user_id: int) -> int:
    """Count library images generated by user_id in the last 7 days (rolling window).

    Uses a Python-side metadata check for broad SQLite/PostgreSQL compatibility.
    """
    cutoff = datetime.utcnow() - timedelta(days=7)
    char_ids = [
        r[0]
        for r in db.query(Character.id).filter(Character.owner_id == user_id).all()
    ]
    if not char_ids:
        return 0
    rows = (
        db.query(CharacterImage)
        .filter(
            CharacterImage.character_id.in_(char_ids),
            CharacterImage.created_at >= cutoff,
        )
        .all()
    )
    return sum(1 for r in rows if (r.metadata_json or {}).get("library") is True)


def _image_error(
    http_status: int,
    *,
    detail: str,
    hint: str,
    provider: str,
) -> HTTPException:
    """Build a structured JSON image error HTTPException."""
    return HTTPException(
        status_code=http_status,
        detail={
            "error": "image_failed",
            "detail": detail,
            "hint": hint,
            "provider": provider,
            "model": settings.IMAGE_MODEL,
        },
    )


def _persist_library_image(
    db: Session,
    character_id: int,
    file_path: str,
    provider: str,
    prompt: str,
) -> CharacterImageRead:
    """Save a generated library image row and return the read schema."""
    data = CharacterImageCreate(
        kind=ImageKindEnum.GENERATED,
        status=ImageStatusEnum.ACTIVE,
        file_path=file_path,
        provider=provider,
        prompt_summary=prompt[:80],
        metadata_json={"library": True, "prompt": prompt},
    )
    return create_character_image(db, character_id, data)


# ── Routes ────────────────────────────────────────────────────────────────────

@router.post("/generate", response_model=CharacterImageRead)
def generate_library_image(
    body: ImageGenerateRequest,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """Generate an image and save it to the user's image library.

    Provider chain (in order):
    1. OpenAI (when IMAGE_PROVIDER=openai and OPENAI_API_KEY is set)
    2. fal.ai fallback (when FAL_KEY is set)
    3. Stub placeholder — ONLY when IMAGE_PROVIDER=stub (test / dev mode)

    Returns a 503 JSON error when the configured provider has no API key.
    Returns a 502 JSON error when all configured providers fail.
    Returns a 429 JSON error when the user's weekly quota is exhausted.
    """
    character = _pick_character(db, current_user)

    # ── Quota check (before any provider call) ────────────────────────────────
    limit = settings.IMAGE_WEEKLY_LIMIT
    if limit > 0:
        used = _count_weekly_library_images(db, current_user.id)
        if used >= limit:
            raise HTTPException(
                status_code=status.HTTP_429_TOO_MANY_REQUESTS,
                detail={
                    "error": "quota_exceeded",
                    "detail": "Weekly image generation limit reached.",
                    "hint": f"You can generate more images next week. Limit: {limit}/week.",
                    "limit": limit,
                    "used": used,
                },
            )

    provider_cfg = settings.IMAGE_PROVIDER.lower()

    # ── Stub mode (test / dev) ────────────────────────────────────────────────
    if provider_cfg == "stub":
        label = body.prompt[:40] + ("…" if len(body.prompt) > 40 else "")
        file_path = generate_placeholder_png(
            label=label,
            sublabel="Ficshon Library",
            role="generated",
        )
        return _persist_library_image(db, character.id, file_path, "stub", body.prompt)

    # ── Primary: OpenAI ───────────────────────────────────────────────────────
    if provider_cfg == "openai":
        if not settings.OPENAI_API_KEY:
            raise _image_error(
                status.HTTP_503_SERVICE_UNAVAILABLE,
                detail="Image provider is not configured.",
                hint=(
                    "Set OPENAI_API_KEY in your environment to enable image generation, "
                    "or set IMAGE_PROVIDER=stub for local development."
                ),
                provider="openai",
            )
        try:
            primary = get_image_provider()
            png_bytes = primary.generate_image(prompt=body.prompt)
            file_path = _save_png_bytes(png_bytes)
            logger.info(
                "library_image generated provider=openai prompt_len=%d", len(body.prompt)
            )
            return _persist_library_image(db, character.id, file_path, "openai", body.prompt)
        except (RuntimeError, ValueError) as exc:
            logger.warning(
                "library_image openai_failed prompt_len=%d err=%s", len(body.prompt), exc
            )
            # Fall through to fal.ai fallback

    # ── Fallback: fal.ai ──────────────────────────────────────────────────────
    fallback = get_fallback_provider()
    if fallback is not None:
        try:
            png_bytes = fallback.generate_image(prompt=body.prompt)
            file_path = _save_png_bytes(png_bytes)
            logger.info(
                "library_image generated provider=fal prompt_len=%d", len(body.prompt)
            )
            return _persist_library_image(db, character.id, file_path, "fal", body.prompt)
        except (RuntimeError, ValueError) as exc:
            logger.warning(
                "library_image fal_failed prompt_len=%d err=%s", len(body.prompt), exc
            )

    # ── All providers exhausted ───────────────────────────────────────────────
    raise _image_error(
        status.HTTP_502_BAD_GATEWAY,
        detail="Image generation failed. All providers are currently unavailable.",
        hint="Try again in a moment, or contact support if the problem persists.",
        provider=provider_cfg,
    )


@router.get("/", response_model=list[CharacterImageRead])
def list_library_images(
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """List the current user's library images (newest first)."""
    char_ids = [
        r[0]
        for r in db.query(Character.id)
        .filter(Character.owner_id == current_user.id)
        .all()
    ]
    if not char_ids:
        return []
    images = (
        db.query(CharacterImage)
        .filter(
            CharacterImage.character_id.in_(char_ids),
            CharacterImage.metadata_json["library"].as_boolean() == True,  # noqa: E712
        )
        .order_by(CharacterImage.created_at.desc())
        .all()
    )
    return images
