"""StoryLab backend loop — state management + provider-routed generation + chapters.

Routes
------
GET  /storylab/state?story_id=...                      Return (or create) story state.
POST /storylab/generate                                 Generate continuation + update state.
GET  /storylab/chapters?story_id=...                   List all chapters for a story.
GET  /storylab/chapters/{chapter_number}?story_id=...  Get a specific chapter.
POST /storylab/chapters/generate?story_id=...          Generate a new chapter.
DELETE /storylab/chapters/{chapter_number}?story_id=... Delete a chapter.
POST /storylab/chapters/{chapter_number}/regenerate?story_id=... Overwrite chapter with new generation.

Generation is delegated to app.services.storylab_generator which routes to
the configured provider (stub / openrouter) with automatic stub fallback.
"""
import json
import logging
import re
import uuid
from datetime import datetime, timedelta, timezone
from typing import Any

from fastapi import APIRouter, Depends, HTTPException, Query
from sqlalchemy.orm import Session

from app.core.config import settings
from app.core.database import get_db
from app.core.dependencies import get_current_user, user_is_admin
from app.core.entitlements import require_creator
from app.models.character import Character as CharacterModel
from app.models.realm import Realm, RealmMembership
from app.models.storylab import (
    GenerationLog,
    GenerationTelemetry,
    Story as StoryModel,
    StoryChapter,
    StoryState,
)
from app.models.user import User
from app.schemas.storylab import (
    Boundary,
    ChapterDetail,
    ChapterGenerateRequest,
    ChapterGenerateResponse,
    ChapterListItem,
    Direction,
    RPReplyGenerateRequest,
    RPReplyGenerateResponse,
    SafetyInfo,
    StateDelta,
    StoryCreateRequest,
    StoryLabGenerateRequest,
    StoryLabGenerateResponse,
    StoryLabStateResponse,
    StoryLabStateSnapshot,
    StoryResponse,
    GeneratedText,
)
from app.services import storylab_telemetry
from app.services.story_memory import (
    check_for_contradictions,
    extract_and_merge_memory,
    seed_memory_from_story_creation,
)
from app.services.storylab_generator import (
    extract_ending_phrase,
    generate_chapter,
    generate_rp_reply,
    generate_story_summary,
    generate_storylab_continuation,
    get_effective_story_model,
    _fallback_suggestions,
    _check_rp_reply_output,
    _rp_length_profile,
)
from app.services.rp_behavior_engine import detect_partner_control, detect_partner_silence_severe, detect_scene_stall, score_inferno_anatomy_density
from app.services.rp_scene_engine import (
    detect_scene_beats,
    detect_repeated_beats,
    determine_next_scene_goal,
    detect_scene_regression,
)
from app.services.rp_escalation import (
    compute_scene_stage,
    detect_scene_resolution,
    get_pacing_warnings,
    score_collaborative_continuation,
)
from app.services.rp_models import effective_heat_level, evaluate_rp_reply_quality
from app.services.rp_beat_planner import detect_multi_beat_instruction, extract_requested_beats, beat_completion_mode
from app.services.rp_spatial_engine import detect_spatial_state
from app.services.rp_style_engine import DEFAULT_ARCHETYPE, detect_ai_cadence
from app.services.rp_narrative_engine import (
    detect_scene_mechanics,
    detect_scene_progression_events,
    detect_paragraph_monotony,
)

logger = logging.getLogger(__name__)
router = APIRouter()

_MAX_TEXT_LENGTH = 50_000

# ── default state ─────────────────────────────────────────────────────────────

_DEFAULT_STATE: dict[str, Any] = {
    "story_state": {
        "tone": "neutral",
        "pacing": "balanced",
        "stakes": 0.2,
        "scene_type": "start",
        "intimacy_level": 0,
        "tension": 0.2,
        "emotional_weight": 0.1,
    },
    "characters": [],
    "relationships": [],
    "memory": {
        "canon": {"hard_truths": [], "world_rules": [], "forbidden_contradictions": []},
        "characters": {},
        "relationships": [],
        "open_threads": [],
        "recent_events": [],
    },
}

# ── quota helpers ─────────────────────────────────────────────────────────────


def _count_daily_chapters_for_user(user_id: str, db: Session) -> int:
    """Return the number of chapters generated by *user_id* since UTC midnight today."""
    today_start = datetime.now(timezone.utc).replace(hour=0, minute=0, second=0, microsecond=0)
    # Strip timezone for comparison with naive UTC datetimes stored in the DB
    cutoff = today_start.replace(tzinfo=None)
    return (
        db.query(StoryChapter)
        .filter(
            StoryChapter.user_id == user_id,
            StoryChapter.created_at >= cutoff,
        )
        .count()
    )


def _seconds_until_utc_midnight() -> int:
    """Seconds until the next UTC midnight (i.e. when the daily quota resets)."""
    now = datetime.now(timezone.utc)
    tomorrow = now.replace(hour=0, minute=0, second=0, microsecond=0) + timedelta(days=1)
    return max(0, int((tomorrow - now).total_seconds()))


# ── telemetry persistence (S24AZ) ──────────────────────────────────────────────

def _persist_generation_telemetry(
    db: Session,
    *,
    user_id: int | None,
    story_id: str | None,
    request_id: str | None,
) -> None:
    """Drain the thread-local telemetry sink and persist one row per generation kind.

    Aggregates sub-calls of the same kind (e.g. a chapter's retries) into a single
    row. Non-fatal: telemetry must never break a generation response.
    """
    try:
        records = storylab_telemetry.drain()
        if not records:
            return
        now = datetime.utcnow()
        for kind, agg in storylab_telemetry.aggregate_by_kind(records).items():
            db.add(
                GenerationTelemetry(
                    user_id=user_id,
                    story_id=story_id,
                    request_id=request_id,
                    kind=kind,
                    provider=agg.get("provider"),
                    model=agg.get("model"),
                    calls=agg.get("calls", 0),
                    prompt_tokens=agg.get("prompt_tokens"),
                    completion_tokens=agg.get("completion_tokens"),
                    total_tokens=agg.get("total_tokens"),
                    cost_usd=agg.get("cost_usd"),
                    created_at=now,
                )
            )
        db.commit()
    except Exception as exc:  # noqa: BLE001 — telemetry is best-effort
        logger.warning("[SL-TELEMETRY] persist failed story_id=%s: %s", story_id, exc)
        try:
            db.rollback()
        except Exception:  # noqa: BLE001
            pass


def _count_daily_telemetry_for_user(user_id: int, kind: str, db: Session) -> int:
    """Count this user's telemetry rows of *kind* since UTC midnight today.

    One row is written per request per kind, so this is a per-request daily count.
    Used as the daily-quota counter for continuation and RP-reply requests.
    """
    today_start = datetime.now(timezone.utc).replace(hour=0, minute=0, second=0, microsecond=0)
    cutoff = today_start.replace(tzinfo=None)
    return (
        db.query(GenerationTelemetry)
        .filter(
            GenerationTelemetry.user_id == user_id,
            GenerationTelemetry.kind == kind,
            GenerationTelemetry.created_at >= cutoff,
        )
        .count()
    )


def _daily_quota_error(used: int, limit: int, label: str) -> HTTPException:
    reset = _seconds_until_utc_midnight()
    return HTTPException(
        status_code=429,
        detail={
            "error": "quota_exceeded",
            "detail": f"Daily {label} limit reached ({used}/{limit}).",
            "hint": "Limit resets at midnight UTC.",
            "reset_in_seconds": reset,
            "limit": limit,
            "used": used,
        },
    )


def _storylab_quota_error(used: int, limit: int) -> HTTPException:
    reset = _seconds_until_utc_midnight()
    return HTTPException(
        status_code=429,
        detail={
            "error": "quota_exceeded",
            "detail": f"Daily chapter limit reached ({used}/{limit}).",
            "hint": "Limit resets at midnight UTC.",
            "reset_in_seconds": reset,
            "limit": limit,
            "used": used,
        },
    )


# ── explicit-content admin gate (S24D FIX 3) ───────────────────────────────────
# For launch, non-SFW text generation is ADMIN-ONLY (no age/eligibility system
# exists yet). SFW generation is unchanged for all users. Enforced server-side on
# every path that honours a non-SFW boundary or elevated (inferno) RP-reply heat.

# Non-SFW story boundaries — everything except Boundary.sfw.
_EXPLICIT_BOUNDARIES = {Boundary.fade_to_black, Boundary.sensual}


def _is_admin_user(user: User) -> bool:
    """True when the user is an admin (DB flag or ADMIN_EMAILS config)."""
    return user_is_admin(user)


def _explicit_admin_only_error(control: str, value: str) -> HTTPException:
    return HTTPException(
        status_code=403,
        detail={
            "error": "explicit_admin_only",
            "detail": (
                f"{control} '{value}' is restricted to admin accounts during launch. "
                "Use an SFW setting."
            ),
        },
    )


def _require_admin_for_boundary(boundary: "Boundary", user: User) -> None:
    """Reject non-SFW boundaries for non-admin users (SFW passes for everyone)."""
    if boundary in _EXPLICIT_BOUNDARIES and not _is_admin_user(user):
        raise _explicit_admin_only_error("boundary", str(getattr(boundary, "value", boundary)))


def _require_admin_for_heat(resolved_heat: str, user: User) -> None:
    """Reject elevated (inferno) RP-reply heat for non-admin users."""
    if resolved_heat == "inferno" and not _is_admin_user(user):
        raise _explicit_admin_only_error("heat level", "inferno")


# ── state mutation helpers ────────────────────────────────────────────────────

_BOUNDARY_INTIMACY_CAP = {
    Boundary.sfw: 2,
    Boundary.fade_to_black: 5,
    Boundary.sensual: 8,
}


def _build_deltas(
    direction: Direction,
    boundary: Boundary,
    state: dict[str, Any],
) -> tuple[dict[str, Any], list[StateDelta]]:
    """Apply conservative state mutations; return updated state + delta list."""
    s = {k: v for k, v in state.items()}
    story = dict(s.get("story_state", {}))
    deltas: list[StateDelta] = []

    def _nudge(field: str, amount: float, cap: float = 1.0, floor: float = 0.0) -> None:
        old = float(story.get(field, 0))
        new = min(cap, max(floor, old + amount))
        if abs(new - old) > 0.001:
            story[field] = round(new, 3)
            deltas.append(StateDelta(path=f"story_state.{field}", delta=round(new - old, 3)))

    if direction == Direction.sad_moment:
        _nudge("emotional_weight", 0.1, cap=1.0)
        _nudge("tension", 0.05)
    elif direction == Direction.argument_begins:
        _nudge("tension", 0.15)
    elif direction in (Direction.romantic_moment, Direction.sensual_scene, Direction.intimate_scene):
        cap = float(_BOUNDARY_INTIMACY_CAP.get(boundary, 2))
        old_il = float(story.get("intimacy_level", 0))
        new_il = min(cap, old_il + 1.0)
        if abs(new_il - old_il) > 0.001:
            story["intimacy_level"] = round(new_il, 1)
            deltas.append(StateDelta(path="story_state.intimacy_level", delta=round(new_il - old_il, 1)))
    elif direction in (Direction.advance_plot, Direction.twist_event):
        _nudge("stakes", 0.1, cap=1.0)
        _nudge("tension", 0.05)
    elif direction == Direction.action_sequence:
        _nudge("tension", 0.2)
    elif direction == Direction.quiet_reflection:
        _nudge("tension", -0.1, floor=0.0)

    s["story_state"] = story
    return s, deltas


# ── model delta merge ─────────────────────────────────────────────────────────

_ALLOWED_DELTA_KEYS: dict[str, str] = {
    "tension_delta": "tension",
    "emotional_weight_delta": "emotional_weight",
    "intimacy_delta": "intimacy_level",
    "stakes_delta": "stakes",
}
_DELTA_CLAMP = 0.2


def apply_model_deltas(
    state: dict[str, Any],
    model_deltas: dict[str, Any],
    boundary: Boundary,
) -> dict[str, Any]:
    """Merge model DELTA_SIGNALS into story_state on top of deterministic baseline.

    Each allowed key is clamped to ±0.2 before being added to the current field
    value. Results are further clamped to [0, 1] (or [0, intimacy_cap] for
    intimacy_level). Unknown keys are silently ignored.
    """
    s = dict(state)
    story = dict(s.get("story_state", {}))
    intimacy_cap = float(_BOUNDARY_INTIMACY_CAP.get(boundary, 2))

    for delta_key, field in _ALLOWED_DELTA_KEYS.items():
        raw = model_deltas.get(delta_key)
        if raw is None:
            continue
        try:
            delta = float(raw)
        except (TypeError, ValueError):
            continue
        delta = max(-_DELTA_CLAMP, min(_DELTA_CLAMP, delta))
        current = float(story.get(field, 0))
        new_val = current + delta
        if field == "intimacy_level":
            new_val = max(0.0, min(intimacy_cap, new_val))
        else:
            new_val = max(0.0, min(1.0, new_val))
        story[field] = round(new_val, 3)

    s["story_state"] = story
    return s


# ── DB helpers ────────────────────────────────────────────────────────────────

def _validate_story_ownership(story_id: str, current_user: User, db: Session) -> "StoryModel | None":
    """Validate that current_user owns the story if a StoryModel record exists.

    Returns the StoryModel when ownership is confirmed.  Returns None when there
    is no StoryModel record for this story_id (legacy ``storylab:`` IDs,
    unregistered scratch IDs) — there is nothing to protect in that case since
    any generated state would be empty/fresh.

    Raises 403 when a StoryModel record exists but belongs to a different user.
    """
    if story_id.startswith("storylab:"):
        # Legacy client-generated IDs have no StoryModel row; skip validation.
        return None
    story = db.query(StoryModel).filter(StoryModel.id == story_id).first()
    if story is None:
        # No record — nothing to protect; state auto-creates empty if needed.
        return None
    if story.user_id != current_user.id:
        raise HTTPException(status_code=403, detail="Not your story")
    return story


def _fetch_recent_endings(
    story_id: str, db: Session, n: int = 3, user_id: int | None = None
) -> list[str]:
    """Return the last *n* ending phrases from the GenerationLog for *story_id*.

    Each entry is the final sentence/line of a past response_text, used to
    populate the prompt's anti-repetition block.  When *user_id* is provided
    and the story_id is a UUID (not a legacy ``storylab:`` ID), the query joins
    through StoryModel to guarantee we only read data for stories owned by that
    user.
    """
    if user_id is not None and not story_id.startswith("storylab:"):
        rows = (
            db.query(GenerationLog.response_text)
            .join(StoryModel, StoryModel.id == GenerationLog.story_id)
            .filter(
                GenerationLog.story_id == story_id,
                StoryModel.user_id == user_id,
            )
            .order_by(GenerationLog.created_at.desc())
            .limit(n)
            .all()
        )
    else:
        rows = (
            db.query(GenerationLog.response_text)
            .filter(GenerationLog.story_id == story_id)
            .order_by(GenerationLog.created_at.desc())
            .limit(n)
            .all()
        )
    endings: list[str] = []
    for (response_text,) in rows:
        if not response_text:
            continue
        phrase = extract_ending_phrase(response_text)
        if phrase:
            endings.append(phrase)
    return endings


def _get_or_create_state(story_id: str, db: Session) -> StoryState:
    row = db.query(StoryState).filter(StoryState.story_id == story_id).first()
    if row is None:
        row = StoryState(
            story_id=story_id,
            story_summary="",
            state_json=_DEFAULT_STATE,
            updated_at=datetime.utcnow(),
        )
        db.add(row)
        db.commit()
        db.refresh(row)
    return row


# ── routes ────────────────────────────────────────────────────────────────────

@router.get("/state", response_model=StoryLabStateResponse)
def get_state(
    story_id: str = Query(..., description="Story workspace identifier"),
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
) -> StoryLabStateResponse:
    """Return the current story state, creating a default row if none exists."""
    _validate_story_ownership(story_id, current_user, db)
    row = _get_or_create_state(story_id, db)
    return StoryLabStateResponse(
        story_id=row.story_id,
        story_summary=row.story_summary or "",
        state_json=row.state_json or _DEFAULT_STATE,
        updated_at=row.updated_at.isoformat(),
    )


@router.post("/generate", response_model=StoryLabGenerateResponse, dependencies=[Depends(require_creator)])
def generate(
    req: StoryLabGenerateRequest,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
) -> StoryLabGenerateResponse:
    """Generate a story continuation and persist updated state."""
    _validate_story_ownership(req.story_id, current_user, db)
    storylab_telemetry.reset()

    # ── daily quota (0 = unlimited) ───────────────────────────────────────────
    _cont_limit = settings.STORYLAB_CONTINUATION_DAILY_LIMIT
    if _cont_limit > 0:
        _used = _count_daily_telemetry_for_user(current_user.id, "continuation", db)
        if _used >= _cont_limit:
            raise _daily_quota_error(_used, _cont_limit, "continuation")

    # ── input validation ──────────────────────────────────────────────────────
    text_stripped = req.text.strip()
    if not text_stripped:
        raise HTTPException(status_code=400, detail="text must not be empty")
    if len(req.text) > _MAX_TEXT_LENGTH:
        raise HTTPException(
            status_code=400,
            detail=f"text exceeds maximum length of {_MAX_TEXT_LENGTH} characters",
        )

    # ── boundary enforcement ──────────────────────────────────────────────────
    # S24D FIX 3: non-SFW boundaries are admin-only during launch.
    _require_admin_for_boundary(req.controls.boundary, current_user)
    _EXPLICIT_DIRECTIONS = {Direction.intimate_scene}
    if (
        req.controls.boundary == Boundary.sfw
        and req.controls.direction in _EXPLICIT_DIRECTIONS
    ):
        raise HTTPException(
            status_code=422,
            detail={
                "code": "BOUNDARY_CONFLICT",
                "message": (
                    f"Direction '{req.controls.direction}' is not permitted "
                    f"under boundary '{req.controls.boundary}'."
                ),
            },
        )

    # ── fetch/create state ────────────────────────────────────────────────────
    state_row = _get_or_create_state(req.story_id, db)
    current_state: dict[str, Any] = dict(state_row.state_json or _DEFAULT_STATE)

    # ── load canon memory ─────────────────────────────────────────────────────
    canon_memory: dict[str, Any] = current_state.get("memory") or {}
    logger.info(
        "[STORY-MEMORY] loaded | story_id=%s hard_truths=%d characters=%d "
        "relationships=%d open_threads=%d",
        req.story_id,
        len((canon_memory.get("canon") or {}).get("hard_truths", [])),
        len(canon_memory.get("characters") or {}),
        len(canon_memory.get("relationships") or []),
        len(canon_memory.get("open_threads") or []),
    )

    # ── fetch recent endings for anti-repetition guidance ─────────────────────
    recent_endings = _fetch_recent_endings(req.story_id, db, user_id=current_user.id)

    # ── generate continuation (provider-routed; stub is fallback) ─────────────
    generated_text, model_deltas = generate_storylab_continuation(
        text=req.text,
        controls=req.controls,
        state_json=current_state,
        summary=state_row.story_summary or "",
        characters=current_state.get("characters", []),
        story_id=req.story_id,
        recent_endings=recent_endings,
        variant=req.variant,
        canon_memory=canon_memory or None,
    )
    word_count = len(generated_text.split())
    request_id = str(uuid.uuid4())

    # ── compute state deltas (deterministic baseline + optional model signals) ─
    new_state, deltas = _build_deltas(req.controls.direction, req.controls.boundary, current_state)
    if model_deltas:
        new_state = apply_model_deltas(new_state, model_deltas, req.controls.boundary)

    # ── persist ───────────────────────────────────────────────────────────────
    state_row.state_json = new_state
    state_row.updated_at = datetime.utcnow()
    db.add(state_row)

    log = GenerationLog(
        story_id=req.story_id,
        request_id=request_id,
        controls_json={
            "direction": req.controls.direction,
            "tone_intensity": req.controls.tone_intensity,
            "pacing": req.controls.pacing,
            "length": req.controls.length,
            "boundary": req.controls.boundary,
        },
        prompt_snapshot=None,
        response_text=generated_text,
        word_count=word_count,
        created_at=datetime.utcnow(),
    )
    db.add(log)
    db.commit()
    db.refresh(state_row)

    # ── telemetry (token + cost) — best-effort, also feeds the daily counter ──
    _persist_generation_telemetry(
        db, user_id=current_user.id, story_id=req.story_id, request_id=request_id
    )

    return StoryLabGenerateResponse(
        request_id=request_id,
        generated=GeneratedText(text=generated_text),
        state=StoryLabStateSnapshot(
            story_summary=state_row.story_summary or "",
            state_json=state_row.state_json,
            deltas=deltas,
        ),
        safety=SafetyInfo(
            blocked=False,
            policy_flags=[],
            boundary=req.controls.boundary,
        ),
        story_model=get_effective_story_model(),
    )


# ── chapter helpers ────────────────────────────────────────────────────────────

def _get_next_chapter_number(story_id: str, db: Session) -> int:
    """Return the next chapter_number for a story (1 if no chapters exist)."""
    from sqlalchemy import func
    result = db.query(func.max(StoryChapter.chapter_number)).filter(
        StoryChapter.story_id == story_id
    ).scalar()
    return (result or 0) + 1


def _chapter_to_list_item(ch: StoryChapter) -> ChapterListItem:
    controls = ch.controls_json or {}
    return ChapterListItem(
        chapter_number=ch.chapter_number,
        created_at=ch.created_at.isoformat(),
        words=ch.word_count,
        mode=ch.mode,
        boundary=controls.get("boundary", "sfw"),
        length=controls.get("length", "medium"),
    )


def _chapter_to_detail(ch: StoryChapter, suggestions: list[str]) -> ChapterDetail:
    return ChapterDetail(
        chapter_number=ch.chapter_number,
        generated_text=ch.generated_text,
        prompt_text=ch.prompt_text or "",
        controls=ch.controls_json or {},
        suggestions=suggestions,
        words=ch.word_count,
        created_at=ch.created_at.isoformat(),
    )


def _build_story_context(
    story_id: str,
    db: Session,
) -> tuple[str, str, str, str, list[dict[str, Any]]]:
    """Fetch story identity, realm description, and character dicts for generation.

    Returns (title, genre, premise, realm_description, story_characters).
    All fields gracefully degrade to empty strings / empty list when data is absent.
    """
    story_obj = db.query(StoryModel).filter(StoryModel.id == story_id).first()
    if not story_obj:
        return "", "", "", "", []

    title = story_obj.title or ""
    genre = story_obj.genre or ""
    premise = story_obj.premise or ""

    # Realm description
    realm_description = ""
    if story_obj.realm_id:
        realm_obj = db.query(Realm).filter(Realm.id == story_obj.realm_id).first()
        if realm_obj:
            parts = [p for p in (realm_obj.name, realm_obj.tagline, realm_obj.description) if p]
            realm_description = " — ".join(parts)

    # Story-bound characters
    story_characters: list[dict[str, Any]] = []
    char_ids = story_obj.character_ids or []
    if char_ids:
        char_rows = (
            db.query(CharacterModel)
            .filter(CharacterModel.id.in_(char_ids))
            .all()
        )
        for c in char_rows:
            entry: dict[str, Any] = {
                "name": c.name or "Unknown",
                "role": c.role or "",
                "short_bio": c.short_bio or "",
                # Additional identity fields for richer protagonist anchor
                "age": c.age or "",
                "species": c.species or "",
                "era": c.era or "",
                "tags": c.tags or "",  # comma-separated trait tags
            }
            # Merge identity_spec_json voice/behaviour fields for richer prompt injection
            if c.identity_spec_json:
                try:
                    spec = (
                        json.loads(c.identity_spec_json)
                        if isinstance(c.identity_spec_json, str)
                        else c.identity_spec_json
                    )
                    if isinstance(spec, dict):
                        for field in (
                            "personality", "traits", "voice", "speech_style", "tone",
                            "motivation", "behavior", "pursuit_style", "never",
                            "power_style", "emotional_pacing",
                        ):
                            val = spec.get(field)
                            if val:
                                entry[field] = val
                except (json.JSONDecodeError, TypeError, AttributeError):
                    pass
            story_characters.append(entry)

    return title, genre, premise, realm_description, story_characters


def _run_chapter_generation(
    story_id: str,
    req: ChapterGenerateRequest,
    db: Session,
    canon_correction_note: str = "",
) -> tuple[str, list[str], dict[str, Any] | None, dict[str, Any]]:
    """Shared generation logic: fetch state, get previous chapter, call generator.

    canon_correction_note — when non-empty, prepended to the user prompt so the
    model is given explicit guidance to correct a prior canon contradiction.
    """
    state_row = _get_or_create_state(story_id, db)
    current_state: dict[str, Any] = dict(state_row.state_json or _DEFAULT_STATE)

    # Last chapter text for continuity context
    last_chapter = (
        db.query(StoryChapter)
        .filter(StoryChapter.story_id == story_id)
        .order_by(StoryChapter.chapter_number.desc())
        .first()
    )
    previous_text = last_chapter.generated_text if last_chapter else None

    # Story-bound context enrichment (gracefully degrades when story/realm/chars absent)
    story_title, story_genre, story_premise, realm_description, story_characters = (
        _build_story_context(story_id, db)
    )

    # ── Load or seed canon memory ─────────────────────────────────────────────
    canon_memory: dict[str, Any] = current_state.get("memory") or {}
    is_first_chapter = last_chapter is None
    if is_first_chapter and not _has_memory_content(canon_memory):
        # Seed memory from story creation inputs on the first chapter
        canon_memory = seed_memory_from_story_creation(
            title=story_title,
            genre=story_genre,
            premise=story_premise,
            characters=story_characters,
        )
        current_state["memory"] = canon_memory

    logger.info(
        "[STORY-MEMORY] loaded | story_id=%s hard_truths=%d characters=%d "
        "relationships=%d open_threads=%d",
        story_id,
        len((canon_memory.get("canon") or {}).get("hard_truths", [])),
        len(canon_memory.get("characters") or {}),
        len(canon_memory.get("relationships") or []),
        len(canon_memory.get("open_threads") or []),
    )

    effective_prompt = req.prompt or ""
    if canon_correction_note:
        effective_prompt = (canon_correction_note + "\n\n" + effective_prompt).strip()

    chapter_text, suggestions, model_deltas = generate_chapter(
        prompt=effective_prompt,
        controls=req.controls,
        state_json=current_state,
        summary=state_row.story_summary or "",
        characters=current_state.get("characters", []),
        previous_chapter_text=previous_text,
        story_id=story_id,
        variant=req.variant,
        story_title=story_title,
        story_genre=story_genre,
        story_premise=story_premise,
        realm_description=realm_description,
        story_characters=story_characters,
        beat_type=req.beat_type,
        canon_memory=canon_memory or None,
    )

    # Update story state (preserve memory key through the delta update)
    new_state, _ = _build_deltas(req.controls.direction, req.controls.boundary, current_state)
    if model_deltas:
        new_state = apply_model_deltas(new_state, model_deltas, req.controls.boundary)
    # Carry forward the canon memory into the new state
    new_state["memory"] = canon_memory
    state_row.state_json = new_state
    state_row.updated_at = datetime.utcnow()
    db.add(state_row)

    return chapter_text, suggestions, model_deltas, canon_memory


def _has_memory_content(memory: dict[str, Any]) -> bool:
    """Return True if the memory dict has any substantive content."""
    if not memory or not isinstance(memory, dict):
        return False
    return bool(
        (memory.get("canon") or {}).get("hard_truths")
        or memory.get("characters")
        or memory.get("open_threads")
    )


def _build_canon_correction_note(
    contradictions: list[str],
    canon_memory: dict[str, Any],
) -> str:
    """Build a targeted, character-specific correction note from detected violations.

    Extracts alive character names from canon_memory and generates explicit rewrite
    instructions that name the specific characters and violation types involved.
    """
    # Collect all confirmed-alive character names
    alive_chars: list[str] = []
    for char_name, char_data in (canon_memory.get("characters") or {}).items():
        status = char_data.get("current_status", [])
        if isinstance(status, list) and any("alive" in str(s).lower() for s in status):
            alive_chars.append(char_name)
    for ht in (canon_memory.get("canon") or {}).get("hard_truths", []):
        if " is alive" in ht.lower():
            nm = ht.split(" is alive")[0].strip()
            if nm and not nm.lower().startswith("story premise:") and nm not in alive_chars:
                alive_chars.append(nm)

    char_str = ", ".join(alive_chars[:3]) if alive_chars else "the main characters"
    many = len(alive_chars) != 1

    has_disappearance = any(
        any(kw in c.lower() for kw in ("disappear", "vanish", "presumed dead", "fake death", "faked"))
        for c in contradictions
    )
    has_death = any(
        any(kw in c.lower() for kw in ("hard canon violated", "kill", "is dead", "died"))
        for c in contradictions
    )
    has_identity_transfer = any("identity transfer" in c.lower() for c in contradictions)

    lines: list[str] = [
        "CANON VIOLATION DETECTED — REWRITE REQUIRED.",
        "The previous generation violated hard canon: " + "; ".join(contradictions[:3]) + ".",
        "",
        f"{char_str} {'are' if many else 'is'} alive in this story. This is absolute hard canon.",
    ]

    if has_disappearance:
        lines.append(
            f"{char_str} {'have' if many else 'has'} NOT disappeared, vanished, or faked"
            f" their death. This is incorrect and must not be written."
            f" If {'they are' if many else 'they are'} absent from another character's life,"
            f" describe it as estrangement, secrecy, distance, or lack of contact —"
            f" NEVER as disappearance, vanishing, going missing, or presumed dead."
        )
    if has_death:
        lines.append(
            f"Do NOT kill, imply the death of, or use past-tense death framing for any"
            f" confirmed-alive character."
        )
    if has_identity_transfer:
        lines.append(
            f"Do NOT imply any character is becoming or inheriting what another character is"
            f" unless the current prompt explicitly instructs this."
        )

    lines.append(
        "Rewrite the chapter from scratch, ensuring every sentence complies with all"
        " canon constraints. Do not repeat any of the listed violations."
    )
    return "\n".join(lines)


def _update_story_summary(
    story_id: str,
    state_row: StoryState,
    chapter_text: str,
    chapter_number: int,
    db: Session,
) -> None:
    """Generate and persist an updated story summary after a chapter is saved.

    Non-fatal: if summarisation fails the chapter is already committed and the
    summary will be regenerated on the next chapter generation.
    """
    try:
        new_summary = generate_story_summary(
            existing_summary=state_row.story_summary or "",
            chapter_text=chapter_text,
            chapter_number=chapter_number,
            story_id=story_id,
        )
        state_row.story_summary = new_summary
        state_row.updated_at = datetime.utcnow()
        db.add(state_row)
        db.commit()
    except Exception as exc:  # noqa: BLE001
        logger.warning("Story summary update failed for %s: %s", story_id, exc)


# ── character memory helpers ───────────────────────────────────────────────────

# Capitalized tokens that should never be treated as character names.
_NAME_BLOCKLIST: frozenset[str] = frozenset({
    "I", "He", "She", "It", "They", "We", "You", "Me", "Him", "Her", "Us",
    "My", "His", "Its", "Our", "Your", "Their", "This", "That", "These",
    "Those", "Which", "Who", "What", "Where", "When", "Why", "How",
    "The", "A", "An", "And", "But", "Or", "Nor", "So", "Yet", "For",
    "As", "If", "Then", "Else", "Than", "Though", "Although", "Not", "No",
    "Yes", "At", "In", "On", "To", "Up", "Of", "By", "From", "With",
    "About", "Into", "Through", "Over", "Under", "After", "Before",
    "Between", "During", "Chapter", "Story", "Scene", "Said", "Asked",
    "Told", "Looked", "Walked", "Turned", "There", "Here", "Still",
    "Even", "Just", "Like", "Well", "Back", "Down", "Out", "Away",
    "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday",
    "January", "February", "March", "April", "May", "June", "July", "August",
    "September", "October", "November", "December",
})

# Minimum times a capitalized token must appear to be treated as a character name.
_STORY_ONLY_MIN_COUNT = 3


def _extract_story_only_names(
    corpus: str,
    matched_name_lowers: set[str],
) -> list[str]:
    """Return a short list of likely character names not already matched to user characters.

    Improved over V1:
    - Captures multi-word capitalized names (e.g. "Lord Blackwood", "Lady Anne")
    - Boosts score for tokens appearing in dialogue attribution patterns
      ("said X", "X said", "asked X", etc.) which are strong name signals
    - Still falls back to single-token frequency with blocklist filtering
    Returns at most 8 candidates.
    """
    # ── Step 1: score single capitalized tokens ───────────────────────────────
    single_pat = re.compile(r'\b([A-Z][a-z]{1,21})\b')
    token_counts: dict[str, int] = {}
    for m in single_pat.finditer(corpus):
        token = m.group(1)
        token_counts[token] = token_counts.get(token, 0) + 1

    # ── Step 2: dialogue-attribution boost (strong name signal) ───────────────
    # Patterns: "said Name", "Name said", "asked Name", "Name asked", etc.
    attr_pat = re.compile(
        r'\b(?:said|asked|told|replied|whispered|shouted|called|cried|muttered|answered)\s+([A-Z][a-z]{1,21})\b'
        r'|'
        r'\b([A-Z][a-z]{1,21})\s+(?:said|asked|told|replied|whispered|shouted|called|cried|muttered|answered)\b'
    )
    attribution_bonus: dict[str, int] = {}
    for m in attr_pat.finditer(corpus):
        token = m.group(1) or m.group(2)
        if token and token not in _NAME_BLOCKLIST:
            attribution_bonus[token] = attribution_bonus.get(token, 0) + 2  # 2× weight

    # ── Step 3: multi-word capitalized names ─────────────────────────────────
    # Capture patterns like "Lord Blackwood", "Lady Anne", "Dr. Morgan"
    multi_pat = re.compile(
        r'\b((?:Lord|Lady|Sir|Dr|Doctor|Professor|Captain|King|Queen|Prince|Princess|Count|Father|Mother|Master|Sergeant|Officer)\s+[A-Z][a-z]{1,21})\b'
    )
    multi_counts: dict[str, int] = {}
    for m in multi_pat.finditer(corpus):
        phrase = m.group(1)
        multi_counts[phrase] = multi_counts.get(phrase, 0) + 1

    # ── Step 4: build candidates ──────────────────────────────────────────────
    # Compute effective score: raw count + attribution bonus
    effective: dict[str, int] = {}
    for token, count in token_counts.items():
        if token in _NAME_BLOCKLIST:
            continue
        if token.lower() in matched_name_lowers:
            continue
        score = count + attribution_bonus.get(token, 0)
        if score < _STORY_ONLY_MIN_COUNT:
            continue
        effective[token] = score

    # Add multi-word names (lower threshold since they're higher signal)
    for phrase, count in multi_counts.items():
        phrase_lower = phrase.lower()
        if phrase_lower in matched_name_lowers:
            continue
        # Deduplicate: if the last word of phrase is already a candidate, prefer phrase
        last_word = phrase.split()[-1]
        if count >= 2:  # slightly lower threshold for titled names
            effective[phrase] = effective.get(phrase, 0) + count * 2
            # Remove bare single-word duplicate if phrase is more specific
            effective.pop(last_word, None)

    candidates = sorted(effective.items(), key=lambda x: -x[1])
    return [name for name, _ in candidates[:8]]


# Relationship signal keyword maps (ordered highest-signal first)
_REL_KEYWORDS: list[tuple[str, list[str]]] = [
    ("conflict", [
        "attacked", "struck", "hit", "fought", "stabbed", "killed", "murdered",
        "threatened", "choked", "punched", "wrestled", "battled",
    ]),
    ("attraction", [
        "kissed", "embraced", "held", "caressed", "longed for", "loved",
        "desired", "attracted", "romantic", "infatuated", "adored",
        "heart raced", "heart skipped", "couldn't stop thinking about",
    ]),
    ("tension", [
        "argued", "shouted", "yelled", "snapped", "glared", "confronted",
        "accused", "hostile", "anger", "furious", "resentment", "bitter",
        "clashed",
    ]),
    ("distrust", [
        "lied", "deceived", "betrayed", "suspicious", "doubted", "didn't trust",
        "couldn't trust", "manipulated", "hidden from", "concealed from",
    ]),
    ("rivalry", [
        "competed", "rival", "jealous", "envied", "outdo", "beat", "bested",
        "one-upped", "outdone",
    ]),
    ("alliance", [
        "helped", "protected", "saved", "trusted", "together", "ally", "allies",
        "relied on", "counted on", "worked together", "side by side", "joined forces",
        "supported",
    ]),
]


def _infer_relationship_type(shared_sentences: list[str]) -> str:
    """Infer the strongest relationship signal from sentences where both names appear.

    Scores each relationship type by keyword hits across all shared sentences.
    Falls back to 'co-present' when no signal meets the minimum threshold.
    """
    scores: dict[str, int] = {}
    combined = " ".join(shared_sentences).lower()
    for rel_type, keywords in _REL_KEYWORDS:
        hits = sum(1 for kw in keywords if kw in combined)
        if hits:
            scores[rel_type] = hits

    if not scores:
        return "co-present"

    # Return the type with highest score
    return max(scores, key=lambda k: scores[k])


def _extract_shared_sentences(text: str, a_lower: str, b_lower: str) -> list[str]:
    """Return sentences (or sentence-like spans) containing both character names."""
    # Split on sentence boundaries
    sentences = re.split(r'(?<=[.!?])\s+', text)
    shared = []
    for sent in sentences:
        sl = sent.lower()
        if a_lower in sl and b_lower in sl:
            shared.append(sent)
    return shared


def _build_relationship_entries(
    char_entries: list[dict[str, Any]],
    chapter_rows: list[tuple[str, int]],
) -> list[dict[str, Any]]:
    """Return relationship entries for matched user character pairs.

    Improved over V1:
    - Infers relationship type from keyword signals in shared sentences
      (conflict, attraction, tension, distrust, rivalry, alliance)
    - Falls back to 'co-present' only when no stronger signal is found
    - Collects shared sentences across all chapters for better signal coverage
    """
    matched = [e for e in char_entries if e.get("source") == "matched_user_character"]
    if len(matched) < 2:
        return []

    rels: list[dict[str, Any]] = []
    seen_pairs: set[tuple[str, str]] = set()

    for i in range(len(matched)):
        for j in range(i + 1, len(matched)):
            name_a = matched[i]["name"]
            name_b = matched[j]["name"]
            pair_key = (min(name_a, name_b), max(name_a, name_b))
            if pair_key in seen_pairs:
                continue
            a_lower = name_a.lower()
            b_lower = name_b.lower()

            shared_sentences: list[str] = []
            appears_together = False
            for ch_text, _ in chapter_rows:
                text = ch_text or ""
                text_lower = text.lower()
                if a_lower in text_lower and b_lower in text_lower:
                    appears_together = True
                    shared_sentences.extend(_extract_shared_sentences(text, a_lower, b_lower))

            if not appears_together:
                continue

            seen_pairs.add(pair_key)
            rel_type = _infer_relationship_type(shared_sentences)
            rels.append({
                "pair": [name_a, name_b],
                "type": rel_type,
                "status": "active",
                "summary": "",
            })

    return rels


# State signals: words near a character name that suggest a non-active state.
_DECEASED_SIGNALS = frozenset({
    "died", "dead", "killed", "murdered", "slain", "perished", "lifeless",
    "body", "corpse", "grave", "buried", "funeral", "death",
})
_ABSENT_SIGNALS = frozenset({
    "vanished", "disappeared", "left", "gone", "fled", "ran away",
    "missing", "escaped", "never returned", "never came back",
})

# Common role-indicator words that may precede a character name in prose
_ROLE_TITLES = frozenset({
    "detective", "doctor", "dr", "nurse", "teacher", "professor", "captain",
    "sergeant", "officer", "guard", "servant", "butler", "maid", "lord",
    "lady", "sir", "count", "king", "queen", "prince", "princess",
    "priest", "bishop", "monk", "general", "colonel", "mayor",
})


def _sentences_with_name(name_lower: str, text: str) -> list[str]:
    """Return all sentences in text that contain name_lower."""
    sentences = re.split(r'(?<=[.!?])\s+', text)
    return [s for s in sentences if name_lower in s.lower()]


def _extract_character_summary(
    name_lower: str,
    chapter_rows: list[tuple[str, int]],
) -> str:
    """Extract a short story-derived summary for a character.

    Finds the most recent chapter containing the character and returns up to
    two sentences that mention them.  Returns empty string when nothing found.
    """
    for ch_text, _ in reversed(chapter_rows):
        if not ch_text or name_lower not in ch_text.lower():
            continue
        hits = _sentences_with_name(name_lower, ch_text)
        if not hits:
            continue
        # Prefer sentences ≥ 30 chars (substantive), cap each at 200 chars
        substantive = [s.strip()[:200] for s in hits if len(s.strip()) >= 30]
        selected = substantive[:2] if substantive else [hits[0].strip()[:200]]
        return " ".join(selected)
    return ""


def _infer_current_state(
    name_lower: str,
    chapter_rows: list[tuple[str, int]],
) -> str:
    """Infer whether a character is active, deceased, or absent.

    Scans the most recent chapter where the character appears, looking for
    death/absence signal words in sentences that mention them.
    Falls back to 'active' when no strong signal found.
    """
    for ch_text, _ in reversed(chapter_rows):
        if not ch_text or name_lower not in ch_text.lower():
            continue
        hits = _sentences_with_name(name_lower, ch_text)
        combined = " ".join(hits).lower()
        if any(sig in combined for sig in _DECEASED_SIGNALS):
            return "deceased"
        if any(sig in combined for sig in _ABSENT_SIGNALS):
            return "absent"
        return "active"
    return "active"


def _infer_story_only_role(name: str, corpus: str) -> str:
    """Infer a story-only character's role from title words near the name.

    Checks for patterns like "the detective [Name]", "[Name] the guard", etc.
    Returns the title as role string, or empty string if none found.
    """
    # Pattern: title word within 3 words before or after the name
    titles_pat = '|'.join(re.escape(t) for t in _ROLE_TITLES)
    title_before = re.compile(
        r'\b(' + titles_pat + r')\.?\s+' + re.escape(name),
        re.IGNORECASE,
    )
    title_after = re.compile(
        re.escape(name) + r'\s*,?\s+(?:the\s+)?(' + titles_pat + r')\b',
        re.IGNORECASE,
    )
    m = title_before.search(corpus) or title_after.search(corpus)
    if m:
        return m.group(1).lower()
    return ""


def _infer_story_only_traits(name: str, corpus: str) -> list[str]:
    """Infer up to 3 traits for a story-only character from descriptive patterns.

    Looks for patterns like:
    - "the [adj] [Name]"  — descriptive noun phrase (adj must not be a role title)
    - "[Name] was/is/seemed [adj]"  — predicative single adjective
    Returns deduplicated lowercase trait list, capped at 3.
    """
    name_esc = re.escape(name)
    # "the [adj] [Name]" — single-word adjective before name (not a role/title word)
    desc_before = re.compile(
        r'\bthe\s+([a-z]{4,20})\s+' + name_esc,
        re.IGNORECASE,
    )
    # "[Name] was/is/seemed/looked [adj]" — single word only (stop at conjunction/punct)
    pred_after = re.compile(
        name_esc + r'\s+(?:was|is|seemed|looked|felt|appeared|became)\s+([a-z]{4,20})\b',
        re.IGNORECASE,
    )
    found: list[str] = []
    for pat in (desc_before, pred_after):
        for m in pat.finditer(corpus):
            trait = m.group(1).lower().strip()
            # Skip role titles, blocklist words, and duplicates
            if (
                trait not in _ROLE_TITLES
                and trait not in _NAME_BLOCKLIST
                and trait not in found
                and len(trait) >= 4
            ):
                found.append(trait)
            if len(found) >= 3:
                break
        if len(found) >= 3:
            break
    return found[:3]


def _update_character_memory(
    story_id: str,
    user_id: str,
    state_row: StoryState,
    db: Session,
) -> None:
    """Rebuild character and relationship memory from all committed chapters.

    Rewrites state_json["characters"] and state_json["relationships"] from
    scratch using the current chapter corpus — safe for both generate and
    regenerate paths (the DB is always up-to-date at call time).

    Non-fatal: any exception is logged and silently swallowed so the
    chapter response is never affected.
    """
    try:
        chapter_rows: list[tuple[str, int]] = (
            db.query(StoryChapter.generated_text, StoryChapter.chapter_number)
            .filter(StoryChapter.story_id == story_id)
            .order_by(StoryChapter.chapter_number)
            .all()
        )
        if not chapter_rows:
            return

        corpus = "\n\n".join(t for t, _ in chapter_rows if t)
        corpus_lower = corpus.lower()

        # ── Fetch user's character roster ────────────────────────────────────
        try:
            owner_id = int(user_id)
        except (TypeError, ValueError):
            owner_id = None

        user_chars = (
            db.query(CharacterModel)
            .filter(CharacterModel.owner_id == owner_id)
            .all()
        ) if owner_id is not None else []

        # ── Matched user characters ───────────────────────────────────────────
        char_entries: list[dict[str, Any]] = []
        matched_name_lowers: set[str] = set()

        for char in user_chars:
            name = (char.name or "").strip()
            alias = (char.alias or "").strip()
            name_hit = bool(name) and name.lower() in corpus_lower
            alias_hit = bool(alias) and alias.lower() in corpus_lower
            if not (name_hit or alias_hit):
                continue

            display_name = name if name_hit else alias
            matched_name_lowers.add(display_name.lower())

            # Last chapter where this character appears
            last_seen = 0
            for ch_text, ch_num in reversed(chapter_rows):
                if display_name.lower() in (ch_text or "").lower():
                    last_seen = ch_num
                    break

            # Traits from identity_spec_json (best-effort)
            traits: list[str] = []
            if char.identity_spec_json:
                try:
                    spec = (
                        json.loads(char.identity_spec_json)
                        if isinstance(char.identity_spec_json, str)
                        else char.identity_spec_json
                    )
                    for field in ("traits", "personality_traits", "personality"):
                        val = spec.get(field)
                        if isinstance(val, list):
                            traits = [str(t).strip() for t in val[:4] if str(t).strip()]
                            break
                        if isinstance(val, str) and val.strip():
                            traits = [v.strip() for v in val.split(",")[:4] if v.strip()]
                            break
                except Exception:  # noqa: BLE001
                    pass

            name_lower = display_name.lower()
            summary = _extract_character_summary(name_lower, chapter_rows)
            current_state = _infer_current_state(name_lower, chapter_rows)

            char_entries.append({
                "name": display_name,
                "source": "matched_user_character",
                "character_id": char.id,
                "role": char.role or "",
                "traits": traits,
                "current_state": current_state,
                "summary": summary,
                "last_seen_in_chapter": last_seen,
            })

        # ── Story-only characters (frequency heuristic) ───────────────────────
        for sname in _extract_story_only_names(corpus, matched_name_lowers):
            sname_lower = sname.lower()
            last_seen = 0
            for ch_text, ch_num in reversed(chapter_rows):
                if sname_lower in (ch_text or "").lower():
                    last_seen = ch_num
                    break
            story_only_summary = _extract_character_summary(sname_lower, chapter_rows)
            story_only_state = _infer_current_state(sname_lower, chapter_rows)
            story_only_role = _infer_story_only_role(sname, corpus)
            story_only_traits = _infer_story_only_traits(sname, corpus)
            char_entries.append({
                "name": sname,
                "source": "story_only",
                "character_id": None,
                "role": story_only_role,
                "traits": story_only_traits,
                "current_state": story_only_state,
                "summary": story_only_summary,
                "last_seen_in_chapter": last_seen,
            })

        # ── Relationships ─────────────────────────────────────────────────────
        rel_entries = _build_relationship_entries(char_entries, chapter_rows)

        # ── Persist ───────────────────────────────────────────────────────────
        current = dict(state_row.state_json or {})
        current["characters"] = char_entries
        current["relationships"] = rel_entries
        state_row.state_json = current
        state_row.updated_at = datetime.utcnow()
        db.add(state_row)
        db.commit()

    except Exception as exc:  # noqa: BLE001
        logger.warning("Character memory update failed for %s: %s", story_id, exc)


def _update_canon_memory(
    story_id: str,
    chapter_text: str,
    chapter_number: int,
    state_row: StoryState,
    db: Session,
) -> None:
    """Extract structured memory from the chapter and persist to state_json["memory"].

    Also runs contradiction detection and logs any violations with [STORY-MEMORY-CONTRADICTION].
    Non-fatal: any exception is logged and swallowed so the chapter response is unaffected.
    """
    try:
        current = dict(state_row.state_json or {})
        existing_memory: dict[str, Any] = current.get("memory") or {}

        # Contradiction check on the generated text before updating memory
        contradictions = check_for_contradictions(chapter_text, existing_memory)
        for contradiction in contradictions:
            logger.warning("[STORY-MEMORY-CONTRADICTION] story_id=%s chapter=%d — %s",
                           story_id, chapter_number, contradiction)

        # Extract and merge new memory from this chapter
        updated_memory = extract_and_merge_memory(
            existing_memory=existing_memory,
            chapter_text=chapter_text,
            chapter_number=chapter_number,
            story_id=story_id,
        )

        current["memory"] = updated_memory
        state_row.state_json = current
        state_row.updated_at = datetime.utcnow()
        db.add(state_row)
        db.commit()

        logger.info(
            "[STORY-MEMORY] Memory updated after chapter %d | story_id=%s "
            "hard_truths=%d characters=%d relationships=%d open_threads=%d",
            chapter_number, story_id,
            len((updated_memory.get("canon") or {}).get("hard_truths", [])),
            len(updated_memory.get("characters") or {}),
            len(updated_memory.get("relationships") or []),
            len(updated_memory.get("open_threads") or []),
        )

    except Exception as exc:  # noqa: BLE001
        logger.warning("[STORY-MEMORY] Canon memory update failed for %s ch%d: %s",
                       story_id, chapter_number, exc)


# ── chapter routes ─────────────────────────────────────────────────────────────

@router.get("/chapters", response_model=list[ChapterListItem])
def list_chapters(
    story_id: str = Query(..., description="Story workspace identifier"),
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
) -> list[ChapterListItem]:
    """Return all chapters for a story, ordered by chapter_number."""
    _validate_story_ownership(story_id, current_user, db)
    user_key = str(current_user.id)
    rows = (
        db.query(StoryChapter)
        .filter(
            StoryChapter.story_id == story_id,
            # Legacy rows have empty user_id; include them only for the owner of the session.
            (StoryChapter.user_id == "") | (StoryChapter.user_id == user_key),
        )
        .order_by(StoryChapter.chapter_number)
        .all()
    )
    return [_chapter_to_list_item(ch) for ch in rows]


@router.get("/chapters/{chapter_number}", response_model=ChapterDetail)
def get_chapter(
    chapter_number: int,
    story_id: str = Query(..., description="Story workspace identifier"),
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
) -> ChapterDetail:
    """Return a specific chapter with suggestions derived from current state."""
    _validate_story_ownership(story_id, current_user, db)
    user_key = str(current_user.id)
    ch = (
        db.query(StoryChapter)
        .filter(
            StoryChapter.story_id == story_id,
            StoryChapter.chapter_number == chapter_number,
            (StoryChapter.user_id == "") | (StoryChapter.user_id == user_key),
        )
        .first()
    )
    if ch is None:
        raise HTTPException(status_code=404, detail="Chapter not found")

    state_row = _get_or_create_state(story_id, db)
    suggestions = _fallback_suggestions(state_row.state_json or _DEFAULT_STATE)
    return _chapter_to_detail(ch, suggestions)


@router.post("/chapters/generate", response_model=ChapterGenerateResponse, dependencies=[Depends(require_creator)])
def generate_chapter_endpoint(
    story_id: str = Query(..., description="Story workspace identifier"),
    req: ChapterGenerateRequest = ...,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
) -> ChapterGenerateResponse:
    """Generate a new chapter and store it."""
    _validate_story_ownership(story_id, current_user, db)
    # S24D FIX 3: non-SFW boundaries are admin-only during launch.
    _require_admin_for_boundary(req.controls.boundary, current_user)
    storylab_telemetry.reset()

    import time as _time
    _endpoint_t0 = _time.time()

    user_key = str(current_user.id)
    limit = settings.STORYLAB_DAILY_LIMIT
    if limit > 0:
        used = _count_daily_chapters_for_user(user_key, db)
        if used >= limit:
            raise _storylab_quota_error(used, limit)

    logger.info(
        "[SL-PATH] generate_chapter_endpoint | story_id=%s length=%s pacing=%s "
        "tone=%s boundary=%s direction=%s mode=%s provider=%s model=%s",
        story_id,
        req.controls.length, req.controls.pacing, req.controls.tone_intensity,
        req.controls.boundary, req.controls.direction, req.mode,
        settings.STORYLAB_PROVIDER, settings.STORYLAB_MODEL,
    )

    # Capture pre-generation canon memory for contradiction checking.
    # For first chapters this will be empty; the seeded memory is returned
    # by _run_chapter_generation as its 4th element and used as fallback.
    _pre_state = _get_or_create_state(story_id, db)
    _pre_memory: dict[str, Any] = (_pre_state.state_json or {}).get("memory") or {}
    # Snapshot pre-generation state_json so we can restore it before any retry,
    # preventing double state-delta application for a single saved chapter.
    _pre_state_json_snapshot: dict[str, Any] = dict(_pre_state.state_json or {})

    try:
        chapter_text, suggestions, model_deltas, _post_memory = _run_chapter_generation(story_id, req, db)
    except HTTPException:
        raise
    except Exception as exc:
        logger.error("StoryLab chapter generation failed for %s: %s", story_id, exc)
        raise HTTPException(
            status_code=502,
            detail={
                "error": "storylab_failed",
                "detail": "Story generation failed. Please try again.",
                "hint": "Check OPENROUTER_API_KEY or try again shortly.",
                "provider": settings.STORYLAB_PROVIDER,
                "model": get_effective_story_model(),
            },
        ) from exc

    if not chapter_text.strip():
        logger.error("StoryLab chapter generation returned empty text for story %s", story_id)
        raise HTTPException(
            status_code=502,
            detail={
                "error": "empty_generation",
                "detail": "Generation produced no text. Please try again.",
                "hint": "The model may have returned an unusable response.",
            },
        )

    word_count = len(chapter_text.split())
    chapter_number = _get_next_chapter_number(story_id, db)

    # ── Blocking canon contradiction check — BEFORE db.commit() ───────────────
    # Use pre-memory when available (chapters 2+); fall back to the seeded
    # post-memory for chapter 1 (where pre-memory is empty before seeding).
    _check_memory = _pre_memory or _post_memory
    if _check_memory:
        contradictions = check_for_contradictions(chapter_text, _check_memory)
        if contradictions:
            logger.warning(
                "[STORY-CANON-BLOCKED] story_id=%s chapter=%d violations=%d"
                " detected_phrases=%s — triggering retry (attempt 2/2).",
                story_id, chapter_number, len(contradictions), contradictions,
            )
            correction_note = _build_canon_correction_note(contradictions, _check_memory)
            try:
                # Restore pre-generation state before retry to prevent double
                # state-delta application for a single chapter.
                _pre_state.state_json = _pre_state_json_snapshot
                db.add(_pre_state)
                logger.info(
                    "[STORY-CANON-RETRY] story_id=%s chapter=%d attempt=2/2.",
                    story_id, chapter_number,
                )
                chapter_text, suggestions, model_deltas, _post_memory = _run_chapter_generation(
                    story_id, req, db, canon_correction_note=correction_note
                )
                retry_contradictions = check_for_contradictions(chapter_text, _check_memory)
                if retry_contradictions:
                    logger.error(
                        "[STORY-CANON-BLOCKED] story_id=%s chapter=%d retry_also_violated=%d"
                        " — refusing to save. violations=%s",
                        story_id, chapter_number, len(retry_contradictions), retry_contradictions,
                    )
                    raise HTTPException(
                        status_code=422,
                        detail={
                            "error": "canon_contradiction",
                            "detail": (
                                "Generated chapter contradicts hard canon and could not be "
                                "corrected automatically. Please adjust your prompt and try again."
                            ),
                            "contradictions": retry_contradictions,
                        },
                    )
                logger.info(
                    "[STORY-CANON-RETRY] story_id=%s chapter=%d retry_succeeded.",
                    story_id, chapter_number,
                )
                word_count = len(chapter_text.split())
            except HTTPException:
                raise
            except Exception as retry_exc:
                logger.error(
                    "[STORY-CANON-BLOCKED] story_id=%s chapter=%d retry_generation_failed: %s"
                    " — refusing to save.",
                    story_id, chapter_number, retry_exc,
                )
                raise HTTPException(
                    status_code=422,
                    detail={
                        "error": "canon_contradiction",
                        "detail": (
                            "Generated chapter contradicts hard canon. "
                            "The correction attempt also failed. Please try again."
                        ),
                        "contradictions": contradictions,
                    },
                ) from retry_exc

    controls_snapshot = {
        "direction": req.controls.direction,
        "tone_intensity": req.controls.tone_intensity,
        "pacing": req.controls.pacing,
        "length": req.controls.length,
        "boundary": req.controls.boundary,
    }
    now = datetime.utcnow()
    ch = StoryChapter(
        story_id=story_id,
        user_id=user_key,
        chapter_number=chapter_number,
        prompt_text=req.prompt or "",
        mode=req.mode,
        controls_json=controls_snapshot,
        generated_text=chapter_text,
        word_count=word_count,
        created_at=now,
        updated_at=now,
    )
    db.add(ch)
    db.commit()
    db.refresh(ch)

    # Update story summary + character memory (both non-fatal; chapter already committed)
    # S24AZ T3: summary is batched to cut per-chapter cost ~20–25%. It fires on
    # the first chapter (so early chapters have summary context) and then only
    # every 3rd chapter thereafter, instead of after every single chapter.
    state_row = _get_or_create_state(story_id, db)
    if chapter_number == 1 or chapter_number % 3 == 0:
        _update_story_summary(story_id, state_row, chapter_text, chapter_number, db)
        state_row = _get_or_create_state(story_id, db)  # re-fetch after summary commit
    _update_character_memory(story_id, user_key, state_row, db)

    # ── Canon memory extraction + contradiction check (non-fatal) ─────────────
    _update_canon_memory(story_id, chapter_text, chapter_number, state_row, db)

    # ── telemetry: chapter gen + (optional) summary + canon_extract ───────────
    _persist_generation_telemetry(
        db, user_id=current_user.id, story_id=story_id, request_id=None
    )

    _endpoint_ms = int((_time.time() - _endpoint_t0) * 1000)
    _using_stub = chapter_text.startswith("[DEV-STUB-FALLBACK]") or (model_deltas is None and settings.STORYLAB_PROVIDER == "stub")
    logger.info(
        "[SL-PATH] generate_chapter_endpoint COMPLETE | story_id=%s chapter=%d "
        "word_count=%d endpoint_ms=%d using_stub=%s",
        story_id, chapter_number, word_count, _endpoint_ms, _using_stub,
    )
    if _endpoint_ms < 1500 and settings.STORYLAB_PROVIDER == "openrouter":
        logger.warning(
            "[SL-PATH] SUSPICIOUS: endpoint completed in %dms with provider=openrouter — "
            "possible silent fallback to stub. Check SL-DIAG logs above for fallback_reason.",
            _endpoint_ms,
        )

    return ChapterGenerateResponse(
        chapter_number=chapter_number,
        generated_text=chapter_text,
        prompt_text=req.prompt or "",
        suggestions=suggestions,
        meta={
            "words": word_count,
            "delta": model_deltas,
            "story_model": get_effective_story_model(),
            "diag": {
                "provider": settings.STORYLAB_PROVIDER,
                "model": get_effective_story_model(),
                "endpoint_ms": _endpoint_ms,
                "length": req.controls.length,
                "pacing": req.controls.pacing,
                "tone": req.controls.tone_intensity,
                "using_stub": _using_stub,
            },
        },
    )


@router.delete("/chapters/{chapter_number}", status_code=204)
def delete_chapter(
    chapter_number: int,
    story_id: str = Query(..., description="Story workspace identifier"),
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
) -> None:
    """Delete a chapter. Gaps in chapter_number are preserved (no renumbering)."""
    ch = (
        db.query(StoryChapter)
        .filter(
            StoryChapter.story_id == story_id,
            StoryChapter.chapter_number == chapter_number,
        )
        .first()
    )
    if ch is None:
        raise HTTPException(status_code=404, detail="Chapter not found")
    # Ownership check: only the chapter author or an admin may delete.
    # ch.user_id may be empty for legacy rows (pre-auth); those are deletable by any authed user.
    is_admin = user_is_admin(current_user)
    if ch.user_id and ch.user_id != str(current_user.id) and not is_admin:
        raise HTTPException(status_code=403, detail="Not your chapter")
    db.delete(ch)
    db.commit()


@router.post("/chapters/{chapter_number}/regenerate", response_model=ChapterGenerateResponse, dependencies=[Depends(require_creator)])
def regenerate_chapter(
    chapter_number: int,
    story_id: str = Query(..., description="Story workspace identifier"),
    req: ChapterGenerateRequest = ...,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
) -> ChapterGenerateResponse:
    """Regenerate a chapter in-place, overwriting its generated_text."""
    _validate_story_ownership(story_id, current_user, db)
    # S24D FIX 3: non-SFW boundaries are admin-only during launch.
    _require_admin_for_boundary(req.controls.boundary, current_user)
    storylab_telemetry.reset()

    user_key = str(current_user.id)
    ch = (
        db.query(StoryChapter)
        .filter(
            StoryChapter.story_id == story_id,
            StoryChapter.chapter_number == chapter_number,
            (StoryChapter.user_id == "") | (StoryChapter.user_id == user_key),
        )
        .first()
    )
    if ch is None:
        raise HTTPException(status_code=404, detail="Chapter not found")

    # ── S24AZ T2-D: regenerate counts against the same daily chapter quota ─────
    # Counts chapter-model generations today (new chapters + regenerations both
    # emit a kind='chapter' telemetry row), so re-rolls can no longer bypass the
    # chapter budget. (Provider=stub writes no telemetry and is free → ungated.)
    limit = settings.STORYLAB_DAILY_LIMIT
    if limit > 0:
        used = _count_daily_telemetry_for_user(current_user.id, "chapter", db)
        if used >= limit:
            raise _storylab_quota_error(used, limit)

    # Capture pre-generation canon memory and state snapshot for contradiction
    # checking and retry (mirrors the generate endpoint pattern).
    _pre_state = _get_or_create_state(story_id, db)
    _pre_memory: dict[str, Any] = (_pre_state.state_json or {}).get("memory") or {}
    _pre_state_json_snapshot: dict[str, Any] = dict(_pre_state.state_json or {})

    try:
        chapter_text, suggestions, model_deltas, _post_memory = _run_chapter_generation(story_id, req, db)
    except HTTPException:
        raise
    except Exception as exc:
        logger.error("StoryLab chapter regeneration failed for %s ch%s: %s", story_id, chapter_number, exc)
        raise HTTPException(
            status_code=502,
            detail={
                "error": "storylab_failed",
                "detail": "Story generation failed. Please try again.",
                "hint": "Check OPENROUTER_API_KEY or try again shortly.",
                "provider": settings.STORYLAB_PROVIDER,
                "model": get_effective_story_model(),
            },
        ) from exc

    if not chapter_text.strip():
        logger.error("StoryLab chapter regeneration returned empty text for story %s ch%s", story_id, chapter_number)
        raise HTTPException(
            status_code=502,
            detail={
                "error": "empty_generation",
                "detail": "Generation produced no text. Please try again.",
                "hint": "The model may have returned an unusable response.",
            },
        )

    word_count = len(chapter_text.split())

    # ── Blocking canon contradiction check — BEFORE db.commit() ───────────────
    _check_memory = _pre_memory or _post_memory
    if _check_memory:
        contradictions = check_for_contradictions(chapter_text, _check_memory)
        if contradictions:
            logger.warning(
                "[STORY-CANON-BLOCKED] regenerate story_id=%s chapter=%d violations=%d"
                " detected_phrases=%s — triggering retry (attempt 2/2).",
                story_id, chapter_number, len(contradictions), contradictions,
            )
            correction_note = _build_canon_correction_note(contradictions, _check_memory)
            try:
                _pre_state.state_json = _pre_state_json_snapshot
                db.add(_pre_state)
                logger.info(
                    "[STORY-CANON-RETRY] regenerate story_id=%s chapter=%d attempt=2/2.",
                    story_id, chapter_number,
                )
                chapter_text, suggestions, model_deltas, _post_memory = _run_chapter_generation(
                    story_id, req, db, canon_correction_note=correction_note
                )
                retry_contradictions = check_for_contradictions(chapter_text, _check_memory)
                if retry_contradictions:
                    logger.error(
                        "[STORY-CANON-BLOCKED] regenerate story_id=%s chapter=%d retry_also_violated=%d"
                        " — refusing to save. violations=%s",
                        story_id, chapter_number, len(retry_contradictions), retry_contradictions,
                    )
                    raise HTTPException(
                        status_code=422,
                        detail={
                            "error": "canon_contradiction",
                            "detail": (
                                "Regenerated chapter contradicts hard canon and could not be "
                                "corrected automatically. Please adjust your prompt and try again."
                            ),
                            "contradictions": retry_contradictions,
                        },
                    )
                logger.info(
                    "[STORY-CANON-RETRY] regenerate story_id=%s chapter=%d retry_succeeded.",
                    story_id, chapter_number,
                )
                word_count = len(chapter_text.split())
            except HTTPException:
                raise
            except Exception as retry_exc:
                logger.error(
                    "[STORY-CANON-BLOCKED] regenerate story_id=%s chapter=%d retry_generation_failed: %s"
                    " — refusing to save.",
                    story_id, chapter_number, retry_exc,
                )
                raise HTTPException(
                    status_code=422,
                    detail={
                        "error": "canon_contradiction",
                        "detail": (
                            "Regenerated chapter contradicts hard canon. "
                            "The correction attempt also failed. Please try again."
                        ),
                        "contradictions": contradictions,
                    },
                ) from retry_exc

    controls_snapshot = {
        "direction": req.controls.direction,
        "tone_intensity": req.controls.tone_intensity,
        "pacing": req.controls.pacing,
        "length": req.controls.length,
        "boundary": req.controls.boundary,
    }
    ch.generated_text = chapter_text
    ch.word_count = word_count
    ch.prompt_text = req.prompt or ch.prompt_text
    ch.controls_json = controls_snapshot
    ch.updated_at = datetime.utcnow()
    db.add(ch)
    db.commit()

    # Update story summary + character memory (both non-fatal; chapter already committed)
    # S24AZ T3: summary is batched to cut per-chapter cost ~20–25%. It fires on
    # the first chapter (so early chapters have summary context) and then only
    # every 3rd chapter thereafter, instead of after every single chapter.
    state_row = _get_or_create_state(story_id, db)
    if chapter_number == 1 or chapter_number % 3 == 0:
        _update_story_summary(story_id, state_row, chapter_text, chapter_number, db)
        state_row = _get_or_create_state(story_id, db)  # re-fetch after summary commit
    _update_character_memory(story_id, user_key, state_row, db)

    # ── Canon memory extraction + contradiction check (non-fatal) ─────────────
    state_row = _get_or_create_state(story_id, db)  # re-fetch after character memory commit
    _update_canon_memory(story_id, chapter_text, chapter_number, state_row, db)

    # ── telemetry: chapter gen + (optional) summary + canon_extract ───────────
    _persist_generation_telemetry(
        db, user_id=current_user.id, story_id=story_id, request_id=None
    )

    return ChapterGenerateResponse(
        chapter_number=chapter_number,
        generated_text=chapter_text,
        prompt_text=req.prompt or ch.prompt_text or "",
        suggestions=suggestions,
        meta={"words": word_count, "delta": model_deltas},
    )


# ── story routes ──────────────────────────────────────────────────────────────

def _story_to_response(story: StoryModel) -> StoryResponse:
    return StoryResponse(
        id=story.id,
        user_id=story.user_id,
        title=story.title,
        genre=story.genre,
        premise=story.premise,
        realm_id=story.realm_id,
        character_ids=story.character_ids or [],
        cover_color=story.cover_color,
        created_at=story.created_at.isoformat(),
        updated_at=story.updated_at.isoformat(),
    )


@router.post("/stories", response_model=StoryResponse, status_code=201, dependencies=[Depends(require_creator)])
def create_story(
    req: StoryCreateRequest,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
) -> StoryResponse:
    """Create a new Story record with title, genre, premise, and optional realm/cast."""
    # Cap character list
    char_ids = req.character_ids[:4]

    # Validate realm access (owner or member)
    if req.realm_id is not None:
        realm = db.query(Realm).filter(Realm.id == req.realm_id).first()
        if realm is None:
            raise HTTPException(status_code=404, detail="Realm not found")
        is_owner = realm.owner_id == current_user.id
        is_member = db.query(RealmMembership).filter(
            RealmMembership.realm_id == req.realm_id,
            RealmMembership.user_id == current_user.id,
        ).first() is not None
        if not (is_owner or is_member):
            raise HTTPException(status_code=403, detail="You are not a member of that realm")

    # Validate character ownership
    for char_id in char_ids:
        char = db.query(CharacterModel).filter(
            CharacterModel.id == char_id,
            CharacterModel.owner_id == current_user.id,
        ).first()
        if char is None:
            raise HTTPException(
                status_code=403,
                detail=f"Character {char_id} not found or not owned by you",
            )

    # Fetch character objects for memory seeding
    story_char_dicts: list[dict[str, Any]] = []
    for char_id in char_ids:
        char = db.query(CharacterModel).filter(CharacterModel.id == char_id).first()
        if char:
            entry: dict[str, Any] = {
                "name": char.name or "",
                "role": char.role or "",
                "species": char.species or "",
                "short_bio": char.short_bio or "",
                "tags": char.tags or "",
            }
            if char.identity_spec_json:
                try:
                    spec = (
                        json.loads(char.identity_spec_json)
                        if isinstance(char.identity_spec_json, str)
                        else char.identity_spec_json
                    )
                    if isinstance(spec, dict):
                        for field in ("traits", "personality", "personality_traits"):
                            val = spec.get(field)
                            if val:
                                entry["traits"] = val
                                break
                except Exception:  # noqa: BLE001
                    pass
            story_char_dicts.append(entry)

    # Seed initial canon memory from story creation inputs
    seeded_memory = seed_memory_from_story_creation(
        title=req.title.strip(),
        genre=req.genre or "",
        premise=req.premise or "",
        characters=story_char_dicts,
    )

    now = datetime.utcnow()
    story = StoryModel(
        id=str(uuid.uuid4()),
        user_id=current_user.id,
        title=req.title.strip(),
        genre=req.genre,
        premise=req.premise,
        realm_id=req.realm_id,
        character_ids=char_ids,
        cover_color=req.cover_color or "#1a1a2e",
        created_at=now,
        updated_at=now,
    )
    db.add(story)
    db.commit()
    db.refresh(story)

    # Create StoryState with seeded memory
    initial_state = dict(_DEFAULT_STATE)
    initial_state["memory"] = seeded_memory
    state_row = StoryState(
        story_id=story.id,
        story_summary="",
        state_json=initial_state,
        updated_at=now,
    )
    db.add(state_row)
    db.commit()

    return _story_to_response(story)


@router.get("/stories", response_model=list[StoryResponse])
def list_stories(
    limit: int = Query(default=50, le=100),
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
) -> list[StoryResponse]:
    """Return all stories owned by the current user, most recently updated first."""
    stories = (
        db.query(StoryModel)
        .filter(StoryModel.user_id == current_user.id)
        .order_by(StoryModel.updated_at.desc())
        .limit(limit)
        .all()
    )
    return [_story_to_response(s) for s in stories]


@router.get("/stories/{story_id}", response_model=StoryResponse)
def get_story(
    story_id: str,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
) -> StoryResponse:
    """Return a story by ID. Only the owning user may access it."""
    story = db.query(StoryModel).filter(
        StoryModel.id == story_id,
        StoryModel.user_id == current_user.id,
    ).first()
    if story is None:
        raise HTTPException(status_code=404, detail="Story not found")
    return _story_to_response(story)


# ── RP Reply Generator ────────────────────────────────────────────────────────

def _build_rp_character_context(char: "CharacterModel") -> tuple[str, str]:
    """Return (character_name, context_block) for injection into RP reply prompt.

    Uses the same protagonist-anchor approach as build_protagonist_anchor in StoryLab
    chapters: all available identity fields are gathered into a structured block that
    anchors the model in a specific character before any other context.
    """
    name = char.name or ""
    lines: list[str] = []

    # Identity header
    identity_frags: list[str] = []
    if char.role:
        identity_frags.append(char.role)
    if char.age:
        identity_frags.append(char.age)
    if char.species:
        identity_frags.append(char.species)
    if char.era:
        identity_frags.append(char.era)

    header = f"**{name}**" if name else "**Character**"
    if identity_frags:
        header += f" — {', '.join(identity_frags)}"
    lines.append(header)

    # Short bio (primary narrative anchor)
    if char.short_bio:
        lines.append(char.short_bio[:350])

    # Long bio (additional context, capped tighter)
    if char.long_bio and char.long_bio.strip():
        long = char.long_bio.strip()
        if long != (char.short_bio or "").strip():
            lines.append(long[:400])

    # Tags / traits (DB column, comma-separated)
    if char.tags and char.tags.strip():
        lines.append(f"Traits: {char.tags[:180]}")

    # identity_spec_json — extract ALL personality-related fields
    if char.identity_spec_json:
        try:
            spec = (
                json.loads(char.identity_spec_json)
                if isinstance(char.identity_spec_json, str)
                else char.identity_spec_json
            )
            if isinstance(spec, dict):
                _SPEC_FIELDS = [
                    ("personality", "Personality"),
                    ("personality_traits", "Traits"),
                    ("traits", "Traits"),
                    ("voice", "Voice"),
                    ("speech_style", "Speech style"),
                    ("tone", "Tone"),
                    ("motivation", "Drives"),
                    ("emotional_pacing", "Emotional pacing"),
                    ("dominant_submissive", "Dynamic"),
                    ("power_style", "Power dynamic"),
                    ("never", "Would never"),
                ]
                seen_labels: set[str] = set()
                for field, label in _SPEC_FIELDS:
                    if label in seen_labels:
                        continue
                    val = spec.get(field)
                    if not val:
                        continue
                    if isinstance(val, list):
                        val = ", ".join(str(v).strip() for v in val if str(v).strip())
                    val_str = str(val).strip()[:200]
                    if val_str:
                        lines.append(f"{label}: {val_str}")
                        seen_labels.add(label)
        except Exception:  # noqa: BLE001
            pass

    lines.append(
        "\nWrite through this character's specific voice, emotional register, "
        "and worldview. Every action and line of dialogue must belong unmistakably to them."
    )

    return name, "\n".join(lines)


@router.post("/rp-reply/generate", response_model=RPReplyGenerateResponse, dependencies=[Depends(require_creator)])
def generate_rp_reply_endpoint(
    req: RPReplyGenerateRequest,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
) -> RPReplyGenerateResponse:
    """Generate an RP reply as the user's character without controlling the partner character."""
    storylab_telemetry.reset()

    # ── S24AZ T2-B: daily RP-reply quota (0 = unlimited) ──────────────────────
    _rp_limit = settings.RP_REPLY_DAILY_LIMIT
    if _rp_limit > 0:
        _rp_used = _count_daily_telemetry_for_user(current_user.id, "rp_reply", db)
        if _rp_used >= _rp_limit:
            raise _daily_quota_error(_rp_used, _rp_limit, "RP reply")

    character_context: str | None = None
    character_name: str = ""
    canon_summary: str | None = None

    if req.character_id is not None:
        char = db.query(CharacterModel).filter(
            CharacterModel.id == req.character_id,
            CharacterModel.owner_id == current_user.id,
        ).first()
        if char is None:
            raise HTTPException(status_code=404, detail="Character not found")
        character_name, character_context = _build_rp_character_context(char)

    if req.story_id is not None:
        state_row = db.query(StoryState).filter(StoryState.story_id == req.story_id).first()
        if state_row is not None and state_row.story_summary and state_row.story_summary.strip():
            canon_summary = state_row.story_summary.strip()[:600]

    effective_archetype = req.style_archetype or DEFAULT_ARCHETYPE

    # Resolve effective heat level (intensity acts as a floor)
    resolved_heat = effective_heat_level(req.heat_level, req.intensity)
    # S24D FIX 3: elevated (inferno) heat is admin-only during launch. Checked on
    # the RESOLVED heat so an intensity floor can't smuggle inferno past the gate.
    _require_admin_for_heat(resolved_heat, current_user)

    reply, model_used, generation_time_ms, pov_warnings, max_tokens_used, godmod_meta = generate_rp_reply(
        partner_reply=req.partner_reply,
        response_length=req.response_length,
        style_match=req.style_match,
        perspective=req.perspective,
        formatting=req.formatting,
        intensity=req.intensity,
        instructions=req.instructions,
        character_context=character_context,
        canon_summary=canon_summary,
        character_name=character_name,
        model_profile=req.model_profile or "default",
        heat_level=resolved_heat,
        style_archetype=effective_archetype,
        partner_character_name=req.partner_character_name or "",
    )

    warnings = _check_rp_reply_output(reply)
    warnings.extend(pov_warnings)
    quality = evaluate_rp_reply_quality(reply)

    # ── escalation analysis (unified 9-stage) ─────────────────────────────────
    detected_stage = compute_scene_stage(reply)
    continuation_score = score_collaborative_continuation(reply)
    resolution = detect_scene_resolution(reply)
    pacing_warnings = get_pacing_warnings(
        reply_text=reply,
        heat_level=resolved_heat,
        continuation_score=continuation_score,
        resolution=resolution,
    )

    # ── prose/cadence quality analysis ────────────────────────────────────────
    cadence_result = detect_ai_cadence(reply)
    style_warnings = cadence_result["warnings"]

    # ── behavior engine diagnostics ───────────────────────────────────────────
    behavior_diag = detect_partner_control(reply)
    silence_diag = detect_partner_silence_severe(reply)
    stall_diag = detect_scene_stall(reply)
    anatomy_density = score_inferno_anatomy_density(reply) if resolved_heat == "inferno" else 0.0

    # ── scene beat engine diagnostics ─────────────────────────────────────────
    _combined_input = (canon_summary or "") + "\n" + req.partner_reply
    scene_beats_result = detect_scene_beats(_combined_input)
    scene_stage_input = scene_beats_result["scene_stage"]
    next_goal_result = determine_next_scene_goal(scene_stage_input)
    next_scene_goal = next_goal_result["next_goal"]
    rep_result = detect_repeated_beats(reply, _combined_input)
    repetition_score = rep_result["repetition_score"]
    regression = detect_scene_regression(reply, _combined_input)
    progression_success = not regression["progression_failure"] and repetition_score < 0.4

    # ── spatial state diagnostics ─────────────────────────────────────────────
    spatial_state = detect_spatial_state(_combined_input)

    # ── narrative engine diagnostics ──────────────────────────────────────────
    _narr_mechanics = detect_scene_mechanics(reply)
    _narr_events    = detect_scene_progression_events(reply)
    _narr_monotony  = detect_paragraph_monotony(reply)

    # ── beat planner diagnostics ──────────────────────────────────────────────
    _raw_beats = extract_requested_beats(req.instructions or "")
    multi_beat_detected = detect_multi_beat_instruction(req.instructions or "") or len(_raw_beats) >= 4
    requested_beats = _raw_beats if multi_beat_detected else []
    requested_beat_count = len(requested_beats)
    beat_completion_mode_label = beat_completion_mode(requested_beats)

    # ── length profile diagnostics ────────────────────────────────────────────
    partner_words_for_profile = len(req.partner_reply.split())
    _length_profile = _rp_length_profile(req.response_length, partner_words_for_profile)
    resolved_length_profile = str(_length_profile["label"])

    logger.info(
        "[SL-DIAG] rp_reply_endpoint | words=%d warnings=%d model=%s time_ms=%d "
        "length=%s style=%s intensity=%s heat=%s resolved_heat=%s archetype=%s "
        "char_id=%s story_id=%s | "
        "quality length=%.2f dialogue=%.2f repetition=%.2f godmod=%.2f format=%.2f | "
        "stage=%s continuation=%.3f resolved=%s pacing_warns=%d style_warns=%d pov_warns=%d | "
        "partner_control_risk=%.3f silence_severe=%s scene_stall=%.3f progression=%.3f "
        "anatomy_density=%.3f repeated_emotion=%.3f ai_cadence=%s | "
        "scene_stage=%s next_goal=%s rep_score=%.3f prog_success=%s "
        "spatial_pos=%s dominance=%s regression=%s | "
        "narr prog_density=%.3f float_risk=%.3f static_risk=%.3f recur_risk=%.3f "
        "prog_events=%d monotony=%.3f env_density=%.3f",
        len(reply.split()), len(warnings), model_used, generation_time_ms,
        req.response_length, req.style_match, req.intensity, req.heat_level,
        resolved_heat, effective_archetype, req.character_id, req.story_id,
        quality["length_score"], quality["dialogue_score"],
        quality["repetition_score"], quality["godmodding_risk"], quality["format_score"],
        detected_stage, continuation_score, resolution["resolved"],
        len(pacing_warnings), len(style_warnings), len(pov_warnings),
        behavior_diag["partner_control_risk"], silence_diag["severe"], stall_diag["scene_stall_score"],
        stall_diag["progression_score"], anatomy_density,
        stall_diag["repeated_emotion_score"], cadence_result["ai_cadence_risk"],
        scene_stage_input, next_scene_goal, repetition_score, progression_success,
        spatial_state["current_position"], spatial_state["dominance_state"],
        regression["regression_flags"],
        _narr_mechanics["progression_density"], _narr_mechanics["floating_scene_risk"],
        _narr_mechanics["static_scene_risk"], _narr_mechanics["recursive_emotion_risk"],
        _narr_events["progression_event_count"], _narr_monotony["monotony_score"],
        _narr_mechanics["environment_usage_density"],
    )

    # ── telemetry (token + cost) — best-effort, also feeds the daily counter ──
    _persist_generation_telemetry(
        db, user_id=current_user.id, story_id=req.story_id, request_id=None
    )

    return RPReplyGenerateResponse(
        reply=reply,
        warnings=warnings,
        model_used=model_used,
        generation_time_ms=generation_time_ms,
        detected_stage=detected_stage,
        continuation_score=continuation_score,
        resolution_detected=resolution["resolved"],
        pacing_warnings=pacing_warnings,
        style_warnings=style_warnings,
        next_scene_goal=next_scene_goal,
        repetition_score=repetition_score,
        progression_success=progression_success,
        multi_beat_detected=multi_beat_detected,
        requested_beats=requested_beats,
        resolved_length_profile=resolved_length_profile,
        max_tokens_used=max_tokens_used,
        requested_beat_count=requested_beat_count,
        beat_completion_mode=beat_completion_mode_label,
        progression_density=_narr_mechanics["progression_density"],
        floating_scene_risk=_narr_mechanics["floating_scene_risk"],
        static_scene_risk=_narr_mechanics["static_scene_risk"],
        recursive_emotion_risk=_narr_mechanics["recursive_emotion_risk"],
        progression_event_count=_narr_events["progression_event_count"],
        paragraph_monotony=_narr_monotony["monotony_score"],
        environment_usage_density=_narr_mechanics["environment_usage_density"],
        godmod_detected=godmod_meta["detected"],
        godmod_severity=godmod_meta["severity"],
        godmod_warnings=godmod_meta["warnings"],
        ai_cadence_risk=bool(cadence_result["ai_cadence_risk"]),
        spatial_position=str(spatial_state["current_position"]),
        spatial_dominance=str(spatial_state["dominance_state"]),
        resolved_heat=resolved_heat,
    )
