"""StoryLab backend loop — state management + provider-routed generation + chapters.

Routes
------
GET  /storylab/state?story_id=...                      Return (or create) story state.
POST /storylab/generate                                 Generate continuation + update state.
GET  /storylab/chapters?story_id=...                   List all chapters for a story.
GET  /storylab/chapters/{chapter_number}?story_id=...  Get a specific chapter.
POST /storylab/chapters/generate?story_id=...          Generate a new chapter.
DELETE /storylab/chapters/{chapter_number}?story_id=... Delete a chapter.
POST /storylab/chapters/{chapter_number}/regenerate?story_id=... Overwrite chapter with new generation.

Generation is delegated to app.services.storylab_generator which routes to
the configured provider (stub / openrouter) with automatic stub fallback.
"""
import json
import logging
import re
import uuid
from datetime import datetime, timedelta, timezone
from typing import Any

from fastapi import APIRouter, Depends, HTTPException, Query
from sqlalchemy.orm import Session

from app.core.config import settings
from app.core.database import get_db
from app.core.dependencies import get_current_user
from app.models.character import Character as CharacterModel
from app.models.storylab import GenerationLog, StoryChapter, StoryState
from app.models.user import User
from app.schemas.storylab import (
    Boundary,
    ChapterDetail,
    ChapterGenerateRequest,
    ChapterGenerateResponse,
    ChapterListItem,
    Direction,
    SafetyInfo,
    StateDelta,
    StoryLabGenerateRequest,
    StoryLabGenerateResponse,
    StoryLabStateResponse,
    StoryLabStateSnapshot,
    GeneratedText,
)
from app.services.storylab_generator import (
    extract_ending_phrase,
    generate_chapter,
    generate_story_summary,
    generate_storylab_continuation,
    _fallback_suggestions,
)

logger = logging.getLogger(__name__)
router = APIRouter()

_MAX_TEXT_LENGTH = 50_000

# ── default state ─────────────────────────────────────────────────────────────

_DEFAULT_STATE: dict[str, Any] = {
    "story_state": {
        "tone": "neutral",
        "pacing": "balanced",
        "stakes": 0.2,
        "scene_type": "start",
        "intimacy_level": 0,
        "tension": 0.2,
        "emotional_weight": 0.1,
    },
    "characters": [],
    "relationships": [],
}

# ── quota helpers ─────────────────────────────────────────────────────────────


def _count_daily_chapters_for_user(user_id: str, db: Session) -> int:
    """Return the number of chapters generated by *user_id* since UTC midnight today."""
    today_start = datetime.now(timezone.utc).replace(hour=0, minute=0, second=0, microsecond=0)
    # Strip timezone for comparison with naive UTC datetimes stored in the DB
    cutoff = today_start.replace(tzinfo=None)
    return (
        db.query(StoryChapter)
        .filter(
            StoryChapter.user_id == user_id,
            StoryChapter.created_at >= cutoff,
        )
        .count()
    )


def _seconds_until_utc_midnight() -> int:
    """Seconds until the next UTC midnight (i.e. when the daily quota resets)."""
    now = datetime.now(timezone.utc)
    tomorrow = now.replace(hour=0, minute=0, second=0, microsecond=0) + timedelta(days=1)
    return max(0, int((tomorrow - now).total_seconds()))


def _storylab_quota_error(used: int, limit: int) -> HTTPException:
    reset = _seconds_until_utc_midnight()
    return HTTPException(
        status_code=429,
        detail={
            "error": "quota_exceeded",
            "detail": f"Daily chapter limit reached ({used}/{limit}).",
            "hint": "Limit resets at midnight UTC.",
            "reset_in_seconds": reset,
            "limit": limit,
            "used": used,
        },
    )


# ── state mutation helpers ────────────────────────────────────────────────────

_BOUNDARY_INTIMACY_CAP = {
    Boundary.sfw: 2,
    Boundary.fade_to_black: 5,
    Boundary.sensual: 8,
}


def _build_deltas(
    direction: Direction,
    boundary: Boundary,
    state: dict[str, Any],
) -> tuple[dict[str, Any], list[StateDelta]]:
    """Apply conservative state mutations; return updated state + delta list."""
    s = {k: v for k, v in state.items()}
    story = dict(s.get("story_state", {}))
    deltas: list[StateDelta] = []

    def _nudge(field: str, amount: float, cap: float = 1.0, floor: float = 0.0) -> None:
        old = float(story.get(field, 0))
        new = min(cap, max(floor, old + amount))
        if abs(new - old) > 0.001:
            story[field] = round(new, 3)
            deltas.append(StateDelta(path=f"story_state.{field}", delta=round(new - old, 3)))

    if direction == Direction.sad_moment:
        _nudge("emotional_weight", 0.1, cap=1.0)
        _nudge("tension", 0.05)
    elif direction == Direction.argument_begins:
        _nudge("tension", 0.15)
    elif direction in (Direction.romantic_moment, Direction.sensual_scene, Direction.intimate_scene):
        cap = float(_BOUNDARY_INTIMACY_CAP.get(boundary, 2))
        old_il = float(story.get("intimacy_level", 0))
        new_il = min(cap, old_il + 1.0)
        if abs(new_il - old_il) > 0.001:
            story["intimacy_level"] = round(new_il, 1)
            deltas.append(StateDelta(path="story_state.intimacy_level", delta=round(new_il - old_il, 1)))
    elif direction in (Direction.advance_plot, Direction.twist_event):
        _nudge("stakes", 0.1, cap=1.0)
        _nudge("tension", 0.05)
    elif direction == Direction.action_sequence:
        _nudge("tension", 0.2)
    elif direction == Direction.quiet_reflection:
        _nudge("tension", -0.1, floor=0.0)

    s["story_state"] = story
    return s, deltas


# ── model delta merge ─────────────────────────────────────────────────────────

_ALLOWED_DELTA_KEYS: dict[str, str] = {
    "tension_delta": "tension",
    "emotional_weight_delta": "emotional_weight",
    "intimacy_delta": "intimacy_level",
    "stakes_delta": "stakes",
}
_DELTA_CLAMP = 0.2


def apply_model_deltas(
    state: dict[str, Any],
    model_deltas: dict[str, Any],
    boundary: Boundary,
) -> dict[str, Any]:
    """Merge model DELTA_SIGNALS into story_state on top of deterministic baseline.

    Each allowed key is clamped to ±0.2 before being added to the current field
    value. Results are further clamped to [0, 1] (or [0, intimacy_cap] for
    intimacy_level). Unknown keys are silently ignored.
    """
    s = dict(state)
    story = dict(s.get("story_state", {}))
    intimacy_cap = float(_BOUNDARY_INTIMACY_CAP.get(boundary, 2))

    for delta_key, field in _ALLOWED_DELTA_KEYS.items():
        raw = model_deltas.get(delta_key)
        if raw is None:
            continue
        try:
            delta = float(raw)
        except (TypeError, ValueError):
            continue
        delta = max(-_DELTA_CLAMP, min(_DELTA_CLAMP, delta))
        current = float(story.get(field, 0))
        new_val = current + delta
        if field == "intimacy_level":
            new_val = max(0.0, min(intimacy_cap, new_val))
        else:
            new_val = max(0.0, min(1.0, new_val))
        story[field] = round(new_val, 3)

    s["story_state"] = story
    return s


# ── DB helpers ────────────────────────────────────────────────────────────────

def _fetch_recent_endings(story_id: str, db: Session, n: int = 3) -> list[str]:
    """Return the last *n* ending phrases from the GenerationLog for *story_id*.

    Each entry is the final sentence/line of a past response_text, used to
    populate the prompt's anti-repetition block.
    """
    rows = (
        db.query(GenerationLog.response_text)
        .filter(GenerationLog.story_id == story_id)
        .order_by(GenerationLog.created_at.desc())
        .limit(n)
        .all()
    )
    endings: list[str] = []
    for (response_text,) in rows:
        if not response_text:
            continue
        phrase = extract_ending_phrase(response_text)
        if phrase:
            endings.append(phrase)
    return endings


def _get_or_create_state(story_id: str, db: Session) -> StoryState:
    row = db.query(StoryState).filter(StoryState.story_id == story_id).first()
    if row is None:
        row = StoryState(
            story_id=story_id,
            story_summary="",
            state_json=_DEFAULT_STATE,
            updated_at=datetime.utcnow(),
        )
        db.add(row)
        db.commit()
        db.refresh(row)
    return row


# ── routes ────────────────────────────────────────────────────────────────────

@router.get("/state", response_model=StoryLabStateResponse)
def get_state(
    story_id: str = Query(..., description="Story workspace identifier"),
    db: Session = Depends(get_db),
    _current_user: User = Depends(get_current_user),
) -> StoryLabStateResponse:
    """Return the current story state, creating a default row if none exists."""
    row = _get_or_create_state(story_id, db)
    return StoryLabStateResponse(
        story_id=row.story_id,
        story_summary=row.story_summary or "",
        state_json=row.state_json or _DEFAULT_STATE,
        updated_at=row.updated_at.isoformat(),
    )


@router.post("/generate", response_model=StoryLabGenerateResponse)
def generate(
    req: StoryLabGenerateRequest,
    db: Session = Depends(get_db),
    _current_user: User = Depends(get_current_user),
) -> StoryLabGenerateResponse:
    """Generate a story continuation and persist updated state."""
    # ── input validation ──────────────────────────────────────────────────────
    text_stripped = req.text.strip()
    if not text_stripped:
        raise HTTPException(status_code=400, detail="text must not be empty")
    if len(req.text) > _MAX_TEXT_LENGTH:
        raise HTTPException(
            status_code=400,
            detail=f"text exceeds maximum length of {_MAX_TEXT_LENGTH} characters",
        )

    # ── boundary enforcement ──────────────────────────────────────────────────
    _EXPLICIT_DIRECTIONS = {Direction.intimate_scene}
    if (
        req.controls.boundary == Boundary.sfw
        and req.controls.direction in _EXPLICIT_DIRECTIONS
    ):
        raise HTTPException(
            status_code=422,
            detail={
                "code": "BOUNDARY_CONFLICT",
                "message": (
                    f"Direction '{req.controls.direction}' is not permitted "
                    f"under boundary '{req.controls.boundary}'."
                ),
            },
        )

    # ── fetch/create state ────────────────────────────────────────────────────
    state_row = _get_or_create_state(req.story_id, db)
    current_state: dict[str, Any] = dict(state_row.state_json or _DEFAULT_STATE)

    # ── fetch recent endings for anti-repetition guidance ─────────────────────
    recent_endings = _fetch_recent_endings(req.story_id, db)

    # ── generate continuation (provider-routed; stub is fallback) ─────────────
    generated_text, model_deltas = generate_storylab_continuation(
        text=req.text,
        controls=req.controls,
        state_json=current_state,
        summary=state_row.story_summary or "",
        characters=current_state.get("characters", []),
        story_id=req.story_id,
        recent_endings=recent_endings,
        variant=req.variant,
    )
    word_count = len(generated_text.split())
    request_id = str(uuid.uuid4())

    # ── compute state deltas (deterministic baseline + optional model signals) ─
    new_state, deltas = _build_deltas(req.controls.direction, req.controls.boundary, current_state)
    if model_deltas:
        new_state = apply_model_deltas(new_state, model_deltas, req.controls.boundary)

    # ── persist ───────────────────────────────────────────────────────────────
    state_row.state_json = new_state
    state_row.updated_at = datetime.utcnow()
    db.add(state_row)

    log = GenerationLog(
        story_id=req.story_id,
        request_id=request_id,
        controls_json={
            "direction": req.controls.direction,
            "tone_intensity": req.controls.tone_intensity,
            "pacing": req.controls.pacing,
            "length": req.controls.length,
            "boundary": req.controls.boundary,
        },
        prompt_snapshot=None,
        response_text=generated_text,
        word_count=word_count,
        created_at=datetime.utcnow(),
    )
    db.add(log)
    db.commit()
    db.refresh(state_row)

    return StoryLabGenerateResponse(
        request_id=request_id,
        generated=GeneratedText(text=generated_text),
        state=StoryLabStateSnapshot(
            story_summary=state_row.story_summary or "",
            state_json=state_row.state_json,
            deltas=deltas,
        ),
        safety=SafetyInfo(
            blocked=False,
            policy_flags=[],
            boundary=req.controls.boundary,
        ),
    )


# ── chapter helpers ────────────────────────────────────────────────────────────

def _get_next_chapter_number(story_id: str, db: Session) -> int:
    """Return the next chapter_number for a story (1 if no chapters exist)."""
    from sqlalchemy import func
    result = db.query(func.max(StoryChapter.chapter_number)).filter(
        StoryChapter.story_id == story_id
    ).scalar()
    return (result or 0) + 1


def _chapter_to_list_item(ch: StoryChapter) -> ChapterListItem:
    controls = ch.controls_json or {}
    return ChapterListItem(
        chapter_number=ch.chapter_number,
        created_at=ch.created_at.isoformat(),
        words=ch.word_count,
        mode=ch.mode,
        boundary=controls.get("boundary", "sfw"),
        length=controls.get("length", "medium"),
    )


def _chapter_to_detail(ch: StoryChapter, suggestions: list[str]) -> ChapterDetail:
    return ChapterDetail(
        chapter_number=ch.chapter_number,
        generated_text=ch.generated_text,
        prompt_text=ch.prompt_text or "",
        controls=ch.controls_json or {},
        suggestions=suggestions,
        words=ch.word_count,
        created_at=ch.created_at.isoformat(),
    )


def _run_chapter_generation(
    story_id: str,
    req: ChapterGenerateRequest,
    db: Session,
) -> tuple[str, list[str], dict[str, Any] | None]:
    """Shared generation logic: fetch state, get previous chapter, call generator."""
    state_row = _get_or_create_state(story_id, db)
    current_state: dict[str, Any] = dict(state_row.state_json or _DEFAULT_STATE)

    # Last chapter text for continuity context
    last_chapter = (
        db.query(StoryChapter)
        .filter(StoryChapter.story_id == story_id)
        .order_by(StoryChapter.chapter_number.desc())
        .first()
    )
    previous_text = last_chapter.generated_text if last_chapter else None

    chapter_text, suggestions, model_deltas = generate_chapter(
        prompt=req.prompt,
        controls=req.controls,
        state_json=current_state,
        summary=state_row.story_summary or "",
        characters=current_state.get("characters", []),
        previous_chapter_text=previous_text,
        story_id=story_id,
        variant=req.variant,
    )

    # Update story state
    new_state, _ = _build_deltas(req.controls.direction, req.controls.boundary, current_state)
    if model_deltas:
        new_state = apply_model_deltas(new_state, model_deltas, req.controls.boundary)
    state_row.state_json = new_state
    state_row.updated_at = datetime.utcnow()
    db.add(state_row)

    return chapter_text, suggestions, model_deltas


def _update_story_summary(
    story_id: str,
    state_row: StoryState,
    chapter_text: str,
    chapter_number: int,
    db: Session,
) -> None:
    """Generate and persist an updated story summary after a chapter is saved.

    Non-fatal: if summarisation fails the chapter is already committed and the
    summary will be regenerated on the next chapter generation.
    """
    try:
        new_summary = generate_story_summary(
            existing_summary=state_row.story_summary or "",
            chapter_text=chapter_text,
            chapter_number=chapter_number,
            story_id=story_id,
        )
        state_row.story_summary = new_summary
        state_row.updated_at = datetime.utcnow()
        db.add(state_row)
        db.commit()
    except Exception as exc:  # noqa: BLE001
        logger.warning("Story summary update failed for %s: %s", story_id, exc)


# ── character memory helpers ───────────────────────────────────────────────────

# Capitalized tokens that should never be treated as character names.
_NAME_BLOCKLIST: frozenset[str] = frozenset({
    "I", "He", "She", "It", "They", "We", "You", "Me", "Him", "Her", "Us",
    "My", "His", "Its", "Our", "Your", "Their", "This", "That", "These",
    "Those", "Which", "Who", "What", "Where", "When", "Why", "How",
    "The", "A", "An", "And", "But", "Or", "Nor", "So", "Yet", "For",
    "As", "If", "Then", "Else", "Than", "Though", "Although", "Not", "No",
    "Yes", "At", "In", "On", "To", "Up", "Of", "By", "From", "With",
    "About", "Into", "Through", "Over", "Under", "After", "Before",
    "Between", "During", "Chapter", "Story", "Scene", "Said", "Asked",
    "Told", "Looked", "Walked", "Turned", "There", "Here", "Still",
    "Even", "Just", "Like", "Well", "Back", "Down", "Out", "Away",
    "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday",
    "January", "February", "March", "April", "May", "June", "July", "August",
    "September", "October", "November", "December",
})

# Minimum times a capitalized token must appear to be treated as a character name.
_STORY_ONLY_MIN_COUNT = 3


def _extract_story_only_names(
    corpus: str,
    matched_name_lowers: set[str],
) -> list[str]:
    """Return a short list of likely character names not already matched to user characters.

    Uses a simple frequency heuristic on capitalized tokens.  False positives
    are possible but kept low by the blocklist and minimum appearance count.
    Returns at most 8 candidates.
    """
    # Match single capitalised words (2–22 chars).
    pattern = re.compile(r'\b([A-Z][a-z]{1,21})\b')
    counts: dict[str, int] = {}
    for m in pattern.finditer(corpus):
        token = m.group(1)
        counts[token] = counts.get(token, 0) + 1

    candidates: list[tuple[int, str]] = []
    for token, count in counts.items():
        if count < _STORY_ONLY_MIN_COUNT:
            continue
        if token in _NAME_BLOCKLIST:
            continue
        if token.lower() in matched_name_lowers:
            continue
        candidates.append((count, token))

    candidates.sort(key=lambda x: -x[0])
    return [name for _, name in candidates[:8]]


def _build_relationship_entries(
    char_entries: list[dict[str, Any]],
    chapter_rows: list[tuple[str, int]],
) -> list[dict[str, Any]]:
    """Return co-presence relationship entries for matched user character pairs.

    Two matched characters form a relationship entry when they both appear in
    the text of at least one chapter.  Only operates on matched_user_character
    entries to keep noise low.
    """
    matched = [e for e in char_entries if e.get("source") == "matched_user_character"]
    if len(matched) < 2:
        return []

    rels: list[dict[str, Any]] = []
    seen_pairs: set[tuple[str, str]] = set()

    for i in range(len(matched)):
        for j in range(i + 1, len(matched)):
            name_a = matched[i]["name"]
            name_b = matched[j]["name"]
            pair_key = (min(name_a, name_b), max(name_a, name_b))
            if pair_key in seen_pairs:
                continue
            a_lower = name_a.lower()
            b_lower = name_b.lower()
            for ch_text, _ in chapter_rows:
                text_lower = (ch_text or "").lower()
                if a_lower in text_lower and b_lower in text_lower:
                    seen_pairs.add(pair_key)
                    rels.append({
                        "pair": [name_a, name_b],
                        "type": "co-present",
                        "status": "active",
                        "summary": "",
                    })
                    break

    return rels


def _update_character_memory(
    story_id: str,
    user_id: str,
    state_row: StoryState,
    db: Session,
) -> None:
    """Rebuild character and relationship memory from all committed chapters.

    Rewrites state_json["characters"] and state_json["relationships"] from
    scratch using the current chapter corpus — safe for both generate and
    regenerate paths (the DB is always up-to-date at call time).

    Non-fatal: any exception is logged and silently swallowed so the
    chapter response is never affected.
    """
    try:
        chapter_rows: list[tuple[str, int]] = (
            db.query(StoryChapter.generated_text, StoryChapter.chapter_number)
            .filter(StoryChapter.story_id == story_id)
            .order_by(StoryChapter.chapter_number)
            .all()
        )
        if not chapter_rows:
            return

        corpus = "\n\n".join(t for t, _ in chapter_rows if t)
        corpus_lower = corpus.lower()

        # ── Fetch user's character roster ────────────────────────────────────
        try:
            owner_id = int(user_id)
        except (TypeError, ValueError):
            owner_id = None

        user_chars = (
            db.query(CharacterModel)
            .filter(CharacterModel.owner_id == owner_id)
            .all()
        ) if owner_id is not None else []

        # ── Matched user characters ───────────────────────────────────────────
        char_entries: list[dict[str, Any]] = []
        matched_name_lowers: set[str] = set()

        for char in user_chars:
            name = (char.name or "").strip()
            alias = (char.alias or "").strip()
            name_hit = bool(name) and name.lower() in corpus_lower
            alias_hit = bool(alias) and alias.lower() in corpus_lower
            if not (name_hit or alias_hit):
                continue

            display_name = name if name_hit else alias
            matched_name_lowers.add(display_name.lower())

            # Last chapter where this character appears
            last_seen = 0
            for ch_text, ch_num in reversed(chapter_rows):
                if display_name.lower() in (ch_text or "").lower():
                    last_seen = ch_num
                    break

            # Traits from identity_spec_json (best-effort)
            traits: list[str] = []
            if char.identity_spec_json:
                try:
                    spec = (
                        json.loads(char.identity_spec_json)
                        if isinstance(char.identity_spec_json, str)
                        else char.identity_spec_json
                    )
                    for field in ("traits", "personality_traits", "personality"):
                        val = spec.get(field)
                        if isinstance(val, list):
                            traits = [str(t).strip() for t in val[:4] if str(t).strip()]
                            break
                        if isinstance(val, str) and val.strip():
                            traits = [v.strip() for v in val.split(",")[:4] if v.strip()]
                            break
                except Exception:  # noqa: BLE001
                    pass

            char_entries.append({
                "name": display_name,
                "source": "matched_user_character",
                "character_id": char.id,
                "role": char.role or "",
                "traits": traits,
                "current_state": "active",
                "summary": "",
                "last_seen_in_chapter": last_seen,
            })

        # ── Story-only characters (frequency heuristic) ───────────────────────
        for sname in _extract_story_only_names(corpus, matched_name_lowers):
            last_seen = 0
            for ch_text, ch_num in reversed(chapter_rows):
                if sname.lower() in (ch_text or "").lower():
                    last_seen = ch_num
                    break
            char_entries.append({
                "name": sname,
                "source": "story_only",
                "character_id": None,
                "role": "",
                "traits": [],
                "current_state": "active",
                "summary": "",
                "last_seen_in_chapter": last_seen,
            })

        # ── Relationships ─────────────────────────────────────────────────────
        rel_entries = _build_relationship_entries(char_entries, chapter_rows)

        # ── Persist ───────────────────────────────────────────────────────────
        current = dict(state_row.state_json or {})
        current["characters"] = char_entries
        current["relationships"] = rel_entries
        state_row.state_json = current
        state_row.updated_at = datetime.utcnow()
        db.add(state_row)
        db.commit()

    except Exception as exc:  # noqa: BLE001
        logger.warning("Character memory update failed for %s: %s", story_id, exc)


# ── chapter routes ─────────────────────────────────────────────────────────────

@router.get("/chapters", response_model=list[ChapterListItem])
def list_chapters(
    story_id: str = Query(..., description="Story workspace identifier"),
    db: Session = Depends(get_db),
    _current_user: User = Depends(get_current_user),
) -> list[ChapterListItem]:
    """Return all chapters for a story, ordered by chapter_number."""
    rows = (
        db.query(StoryChapter)
        .filter(StoryChapter.story_id == story_id)
        .order_by(StoryChapter.chapter_number)
        .all()
    )
    return [_chapter_to_list_item(ch) for ch in rows]


@router.get("/chapters/{chapter_number}", response_model=ChapterDetail)
def get_chapter(
    chapter_number: int,
    story_id: str = Query(..., description="Story workspace identifier"),
    db: Session = Depends(get_db),
    _current_user: User = Depends(get_current_user),
) -> ChapterDetail:
    """Return a specific chapter with suggestions derived from current state."""
    ch = (
        db.query(StoryChapter)
        .filter(
            StoryChapter.story_id == story_id,
            StoryChapter.chapter_number == chapter_number,
        )
        .first()
    )
    if ch is None:
        raise HTTPException(status_code=404, detail="Chapter not found")

    state_row = _get_or_create_state(story_id, db)
    suggestions = _fallback_suggestions(state_row.state_json or _DEFAULT_STATE)
    return _chapter_to_detail(ch, suggestions)


@router.post("/chapters/generate", response_model=ChapterGenerateResponse)
def generate_chapter_endpoint(
    story_id: str = Query(..., description="Story workspace identifier"),
    req: ChapterGenerateRequest = ...,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
) -> ChapterGenerateResponse:
    """Generate a new chapter and store it."""
    user_key = str(current_user.id)
    limit = settings.STORYLAB_DAILY_LIMIT
    if limit > 0:
        used = _count_daily_chapters_for_user(user_key, db)
        if used >= limit:
            raise _storylab_quota_error(used, limit)

    try:
        chapter_text, suggestions, model_deltas = _run_chapter_generation(story_id, req, db)
    except HTTPException:
        raise
    except Exception as exc:
        logger.error("StoryLab chapter generation failed for %s: %s", story_id, exc)
        raise HTTPException(
            status_code=502,
            detail={
                "error": "storylab_failed",
                "detail": "Story generation failed. Please try again.",
                "hint": "Check OPENROUTER_API_KEY or try again shortly.",
                "provider": settings.STORYLAB_PROVIDER,
                "model": settings.STORYLAB_MODEL,
            },
        ) from exc

    word_count = len(chapter_text.split())
    chapter_number = _get_next_chapter_number(story_id, db)

    controls_snapshot = {
        "direction": req.controls.direction,
        "tone_intensity": req.controls.tone_intensity,
        "pacing": req.controls.pacing,
        "length": req.controls.length,
        "boundary": req.controls.boundary,
    }
    now = datetime.utcnow()
    ch = StoryChapter(
        story_id=story_id,
        user_id=user_key,
        chapter_number=chapter_number,
        prompt_text=req.prompt or "",
        mode=req.mode,
        controls_json=controls_snapshot,
        generated_text=chapter_text,
        word_count=word_count,
        created_at=now,
        updated_at=now,
    )
    db.add(ch)
    db.commit()
    db.refresh(ch)

    # Update story summary + character memory (both non-fatal; chapter already committed)
    state_row = _get_or_create_state(story_id, db)
    _update_story_summary(story_id, state_row, chapter_text, chapter_number, db)
    state_row = _get_or_create_state(story_id, db)  # re-fetch after summary commit
    _update_character_memory(story_id, user_key, state_row, db)

    return ChapterGenerateResponse(
        chapter_number=chapter_number,
        generated_text=chapter_text,
        prompt_text=req.prompt or "",
        suggestions=suggestions,
        meta={"words": word_count, "delta": model_deltas},
    )


@router.delete("/chapters/{chapter_number}", status_code=204)
def delete_chapter(
    chapter_number: int,
    story_id: str = Query(..., description="Story workspace identifier"),
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
) -> None:
    """Delete a chapter. Gaps in chapter_number are preserved (no renumbering)."""
    ch = (
        db.query(StoryChapter)
        .filter(
            StoryChapter.story_id == story_id,
            StoryChapter.chapter_number == chapter_number,
        )
        .first()
    )
    if ch is None:
        raise HTTPException(status_code=404, detail="Chapter not found")
    # Ownership check: only the chapter author or an admin may delete.
    # ch.user_id may be empty for legacy rows (pre-auth); those are deletable by any authed user.
    is_admin = bool(current_user.is_admin) or current_user.email.lower() in settings.get_admin_emails()
    if ch.user_id and ch.user_id != str(current_user.id) and not is_admin:
        raise HTTPException(status_code=403, detail="Not your chapter")
    db.delete(ch)
    db.commit()


@router.post("/chapters/{chapter_number}/regenerate", response_model=ChapterGenerateResponse)
def regenerate_chapter(
    chapter_number: int,
    story_id: str = Query(..., description="Story workspace identifier"),
    req: ChapterGenerateRequest = ...,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
) -> ChapterGenerateResponse:
    """Regenerate a chapter in-place, overwriting its generated_text."""
    ch = (
        db.query(StoryChapter)
        .filter(
            StoryChapter.story_id == story_id,
            StoryChapter.chapter_number == chapter_number,
        )
        .first()
    )
    if ch is None:
        raise HTTPException(status_code=404, detail="Chapter not found")

    user_key = str(current_user.id)
    limit = settings.STORYLAB_DAILY_LIMIT
    if limit > 0:
        used = _count_daily_chapters_for_user(user_key, db)
        if used >= limit:
            raise _storylab_quota_error(used, limit)

    try:
        chapter_text, suggestions, model_deltas = _run_chapter_generation(story_id, req, db)
    except HTTPException:
        raise
    except Exception as exc:
        logger.error("StoryLab chapter regeneration failed for %s ch%s: %s", story_id, chapter_number, exc)
        raise HTTPException(
            status_code=502,
            detail={
                "error": "storylab_failed",
                "detail": "Story generation failed. Please try again.",
                "hint": "Check OPENROUTER_API_KEY or try again shortly.",
                "provider": settings.STORYLAB_PROVIDER,
                "model": settings.STORYLAB_MODEL,
            },
        ) from exc
    word_count = len(chapter_text.split())

    controls_snapshot = {
        "direction": req.controls.direction,
        "tone_intensity": req.controls.tone_intensity,
        "pacing": req.controls.pacing,
        "length": req.controls.length,
        "boundary": req.controls.boundary,
    }
    ch.generated_text = chapter_text
    ch.word_count = word_count
    ch.prompt_text = req.prompt or ch.prompt_text
    ch.controls_json = controls_snapshot
    ch.updated_at = datetime.utcnow()
    db.add(ch)
    db.commit()

    # Update story summary + character memory (both non-fatal; chapter already committed)
    state_row = _get_or_create_state(story_id, db)
    _update_story_summary(story_id, state_row, chapter_text, chapter_number, db)
    state_row = _get_or_create_state(story_id, db)  # re-fetch after summary commit
    _update_character_memory(story_id, user_key, state_row, db)

    return ChapterGenerateResponse(
        chapter_number=chapter_number,
        generated_text=chapter_text,
        prompt_text=req.prompt or ch.prompt_text or "",
        suggestions=suggestions,
        meta={"words": word_count, "delta": model_deltas},
    )
