"""Add Phase 2 fields to Character and Realm

Revision ID: 8b18cfce864f
Revises: f3c9a3f6a7fb
Create Date: 2025-11-16 22:57:37.122773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b18cfce864f'
down_revision: Union[str, None] = 'f3c9a3f6a7fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('role', sa.String(), nullable=True))
    op.add_column('characters', sa.Column('era', sa.String(), nullable=True))
    op.add_column('characters', sa.Column('portrait_url', sa.String(), nullable=True))
    op.add_column('realms', sa.Column('tagline', sa.String(), nullable=True))
    op.add_column('realms', sa.Column('banner_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('realms', 'banner_url')
    op.drop_column('realms', 'tagline')
    op.drop_column('characters', 'portrait_url')
    op.drop_column('characters', 'era')
    op.drop_column('characters', 'role')
    # ### end Alembic commands ###
