"""add_phase_3_connections_and_reaction_constraints

Revision ID: caa49eef2193
Revises: 8b18cfce864f
Create Date: 2025-11-17 15:33:21.079883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caa49eef2193'
down_revision: Union[str, None] = '8b18cfce864f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followee_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['followee_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('follower_id', 'followee_id', name='unique_connection')
    )
    op.create_index(op.f('ix_connections_id'), 'connections', ['id'], unique=False)

    # Use batch mode for SQLite to add constraint to reactions table
    with op.batch_alter_table('reactions', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_user_reaction_per_post', ['post_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reactions', schema=None) as batch_op:
        batch_op.drop_constraint('unique_user_reaction_per_post', type_='unique')

    op.drop_index(op.f('ix_connections_id'), table_name='connections')
    op.drop_table('connections')
    # ### end Alembic commands ###
