"""Add user_id to story_chapter for daily quota tracking

Revision ID: e2f3a4b5c6d7
Revises: b2c3d4e5f6a7
Create Date: 2026-02-28

Adds story_chapter.user_id (nullable FK → users.id, ON DELETE SET NULL).
Used by the StoryLab daily quota check — counts chapters generated by a user
in the last 24 hours.  Existing rows get user_id=NULL and are not counted
against any user's quota (safe migration).
"""
from typing import Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e2f3a4b5c6d7'
down_revision: Union[str, None] = 'b2c3d4e5f6a7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    with op.batch_alter_table("story_chapter") as batch_op:
        batch_op.add_column(
            sa.Column(
                "user_id",
                sa.Integer(),
                sa.ForeignKey("users.id", ondelete="SET NULL"),
                nullable=True,
            )
        )
        batch_op.create_index("ix_story_chapter_user_id", ["user_id"])


def downgrade() -> None:
    with op.batch_alter_table("story_chapter") as batch_op:
        batch_op.drop_index("ix_story_chapter_user_id")
        batch_op.drop_column("user_id")
