"""Add user_id to character_images for weekly quota tracking

Revision ID: f1a2b3c4d5e6
Revises: b2c3d4e5f6a7
Create Date: 2026-02-28

Adds character_images.user_id (nullable FK → users.id, ON DELETE SET NULL).
Used by the image weekly quota check — counts images generated by a user
in the last 7 days.  Existing rows get user_id=NULL and are not counted
against any user's quota (safe migration).
"""
from typing import Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f1a2b3c4d5e6'
down_revision: Union[str, None] = 'b2c3d4e5f6a7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    with op.batch_alter_table("character_images") as batch_op:
        batch_op.add_column(
            sa.Column(
                "user_id",
                sa.Integer(),
                sa.ForeignKey("users.id", ondelete="SET NULL"),
                nullable=True,
            )
        )
        batch_op.create_index("ix_character_images_user_id", ["user_id"])


def downgrade() -> None:
    with op.batch_alter_table("character_images") as batch_op:
        batch_op.drop_index("ix_character_images_user_id")
        batch_op.drop_column("user_id")
